### ISSUE TITLE
`get_alloc_memory` deallocates arguments before the function returns

### ISSUE THREAD

**Issue by shino16** [Lightning-AI/lightning-thunder#1029]
## 🐛 Bug

```py
import torch
import thunder
from thunder.examine.memory_caculation import get_alloc_memory

def f(x):
    z = x + 1
    w = z + 1
    return w

jitted = thunder.jit(f, executors=[])
jitted(torch.zeros(8, dtype=torch.float32, device='cuda'))
print(get_alloc_memory(thunder.last_traces(jitted)[-1]))
```
#### Trace
```py
def computation(x):
  z = torch.add(x, 1)  # z: "cuda:0 f32[8]"
  del x
  w = torch.add(z, 1)  # w: "cuda:0 f32[8]"
  del z
  return w
```
#### Output:
```
(64, {'unpack_trivial x': 32, 'add z': 32, 'python_del x': -32, 'add w': 32, 'python_del z': -32})
```
64 bytes is equivalent to two `f32[8]` tensors, `(x, z)` or `(z, w)`.

#### Expected output:
```
(96, {'unpack_trivial x': 32, 'add z': 32, 'add w': 32, 'python_del z': -32})
```
Equivalent to three `f32[8]` tensors, `(x, z, w)`.

### Why the current output is incorrect

`get_alloc_memory` thinks that `del x` deallocates the tensor behind `x`, so it records `'python_del x': -32`. However, as Python holds the arguments in memory throughout the function call, it cannot be deallocated.

**Comment by IvanYashchuk** [comment]
Yes, this function should take into account Python's behavior of holding arguments in memory throughout the function call. Thank you very much for noticing this problem and preparing a clear example!
