### ISSUE TITLE
Add option to `ThunderCompiler` to save `gm.code` or `gm.print_readable` to file

### ISSUE THREAD

**Issue by crcrpar** [Lightning-AI/lightning-thunder#1082]
### Motivation

It'd be common to see `torch.compile` frontend generates multiple graphs for a model and Thunder fails to interpret and optimize them.
In such case, it'd be helpful if we have an option to save them into files.

### Additional context

cc @apaz-cli

**Comment by tfogal** [comment]
Assigning to me, I've got some things here that I just need to clean up and make a PR out of

**Comment by tfogal** [comment]
As mentioned in #1332, the basic idea is to move this code: https://github.com/tfogal/NeMo/blob/a0c711deae6c6f7342662795425684a342f95b8d/examples/multimodal/multimodal_llm/neva/neva_pretrain.py#L164 into Thunder itself.
