### ISSUE TITLE
AttributeError for Dynamo+Thunder+FP8 and Phi-3-mini-4k-instruct  'GraphModule' object has no attribute 'real_recompile'

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#1091]
## 🐛 Bug
When training Dynamo+Thunder + FP8 we get an attribute error:

> AttributeError: \'GraphModule\' object has no attribute \'real_recompile\'

I'm aware that it's not exected to work yet, but I don't see similar issue, so I'm adding it to track the progress.

Models affected:
'stablecode-completion-alpha-3b', 'Phi-3-mini-4k-instruct', 'pythia-14m', 'Mistral-7B-v0.1', 'dolly-v2-3b', 'falcon-7b', 'tiny-llama-1.1b'

### To Reproduce

Start interactive job on a cluster:
srun -A YOUR_SLURM_ACCOUNT -J YOUR_SLURM_ACCOUNT-thunder.lit-gpt -N1 -p batch --container-image=INTERNAL_IMAGE:pjnl-20240830 --pty bash

Then execute:
torchrun --standalone --max-restarts=0 --no-python --nproc-per-node=8 python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
    --model_name Mistral-7B-v0.1 \
    --distributed_mode ddp \
    --shard_mode None \
    --compile dynamo_thunder \
    --checkpoint_activations False \
    --low_precision_mode fp8-delayed-te  \
    --micro_batch_size 1

### Expected behavior

We should be able to run the training or get OOM error. 

### Environment

system.device_product_name                      DGXH100
system.gpu_driver_version                    535.129.03
libraries.cuda                               12.6.1.005
libraries.pip.lightning               2.4.0.dev20240728
libraries.pip.lightning-thunder              0.2.0.dev0
libraries.pip.lightning-utilities                0.11.6
libraries.pip.litgpt                             0.4.11
libraries.pip.nvfuser                 0.2.10+git58dfdc1
libraries.pip.pytorch-lightning                   2.4.0
libraries.pip.torch                  2.5.0a0+git578b8d7
libraries.pip.torchmetrics                        1.4.1
libraries.pip.torchvision              0.19.0a0+d23a6e1

**Comment by IvanYashchuk** [comment]
This error was encountered due to inconsistencies in Dynamo when using DDP (`--distributed_mode ddp`). From https://github.com/Lightning-AI/lightning-thunder/pull/1094#issuecomment-2328339355:
> > What are the conditions for Dynamo to generate LazyGraphModule and plain GraphModule?

> For the original issue in question because of using DDP, we were going via this path below which returns a GraphModule instead of _LazyGraphModule.
> https://github.com/pytorch/pytorch/blob/39935e0fdef02c67ba808175dcc800d0695bfe1b/torch/_dynamo/backends/distributed.py#L514-L516
