### ISSUE TITLE
TensorProxy.shape should be unpacked automatically

### ISSUE THREAD

**Issue by jjsjann123** [Lightning-AI/lightning-thunder#1253]
## 🐛 Bug

`TensorProxy.shape` remains as an attribute, hence accessing it won't leave an unpack in trace. This causes issues when we have `NumberProxy` in `TensorProxy.shape`.

In #1201 commit 26f883e33f2231c0f04fa5443a5790e892e93c78. I have to rely on [this hack](https://github.com/Lightning-AI/lightning-thunder/blob/26f883e33f2231c0f04fa5443a5790e892e93c78/thunder/clang/__init__.py#L978-L979). Otherwise, grad transform would see an invalid trace,

e.g. in a trivial slice:
```
def foo(a):
  return a[..., : a.shape[-1]]

thunder.jit(foo, cache="symbolic values")
```

```
def computation(a, i1):
  # a: "cpu f32 [IntegerProxy name=i0], [IntegerProxy name=i1]
  # i1: "int 8"
  a = ltorch.getitem(a, (..., slice(None, i1, None))
      # (i0, i1) = prims.shape(a)  # THIS IS WHAT THE HACK DOES
      # b2 = prims.lt(i0, 0)
      # ...
```

Without the explicit unpack of a.shape, the subsymbols in ltorch.getitem would access `i0`, which is implicitly carried by a.shape but not explicitly in the trace.

### Alternative

This problem can also be properly resolved in prologue trace. i.e. here `i1` is unpacked in prologue, because it is consumed by the top level symbol `ltorch.getitem`. Unfortunately the uses of subsymbol is not considered as consumed by computation trace today, see [code](https://github.com/Lightning-AI/lightning-thunder/blob/d6455982d5ca6815efd3d7dc0341b4f945f99be5/thunder/core/jit_ext.py#L1691), so `i0` isn't getting unpacked in prologue yet.

So for input TensorProxy, I think prologue unpacking is the right choice here. For intermediate tensor, it might be a mixed solution, which goes back to the conversation we have in #1133 .

**Comment by t-vi** [comment]
> This problem can also be properly resolved in prologue trace. i.e. here i1 is unpacked in prologue, because it is consumed by the top level symbol ltorch.getitem. Unfortunately the uses of subsymbol is not considered as consumed by computation trace today, see [code](https://github.com/Lightning-AI/lightning-thunder/blob/d6455982d5ca6815efd3d7dc0341b4f945f99be5/thunder/core/jit_ext.py#L1691), so i0 isn't getting unpacked in prologue yet.

I'm a bit skeptical about the alternative here and my gut feeling is that the main solution (to unpack the shape "close" to where it is used is preferable).
To my mind, the alternative solution implies the major change that is that the subsymbols considered as a block of code has inputs that the symbol has not. To my mind, this is tricky on several layers (producers / consumers etc.).

The tricky thing with re-unpacking could be that I'm not sure we are good at having one name assigned to multiple times, so we may need new names every time we do this.

**Comment by jjsjann123** [comment]
I'm closing this one for now since #1260 is merged now.

For the duplicated shape query, I'll open another issue to track that.
