### ISSUE TITLE
LitGPT benchmarking with Dynamo + activation checkpointing creates a graph break

### ISSUE THREAD

**Issue by IvanYashchuk** [Lightning-AI/lightning-thunder#1298]
*Note*: If you have a model or program that is not supported yet but should be, please use the program coverage template.

## 🐛 Bug

Try running
```
TORCH_LOGS="+dynamo" python thunder/benchmarks/benchmark_litgpt.py --model_name longchat-7b-16k --compile dynamo+thunder --n_layers=2 --max_iters=2 --warmup_iters=1 --checkpoint_activations=True
```
and from the logs, we can see that Dynamo fallbacks to eager for executing the checkpointed part instead of passing that to a compiler.

We should find a way how to set up activation checkpointing correctly so that Dynamo passes a single graph in the case of LitGPT to a compiler like Inductor or Thunder.

cc @crcrpar

**Comment by kiya00** [comment]
As mentioned in https://github.com/Lightning-AI/lightning-thunder/pull/1370#issuecomment-2448097800, close this as completed
