### ISSUE TITLE
Support OPT model familly

### ISSUE THREAD

**Issue by mjmikulski** [Lightning-AI/lightning-thunder#1312]
## 🚀 Model / language coverage

I tried using [OPT-125M from Hugging Face](https://huggingface.co/facebook/opt-125m). The compilation went fine, but an error was raised during forward pass.

### Pitch

OPT models are a popular family of models (e.g. `facebook/opt-125m` has 5M+ downloads last month) ranging in sizes from 125M to 175B parameters, [ref.](https://arxiv.org/pdf/2205.01068)

### Minimal Repro

```py
import torch
import thunder
from transformers import AutoModelForCausalLM, AutoTokenizer

# Configuration
BLOCK_SIZE = 500
DEVICE = torch.device('cuda', 0)

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained('facebook/opt-125m')

# Sample data (just a dummy tensor to mimic tokenized data)
input_ids = torch.randint(0, 1000, (1, BLOCK_SIZE), dtype=torch.long, device=DEVICE)

# Model
model = AutoModelForCausalLM.from_pretrained(
    'facebook/opt-125m',
    torch_dtype=torch.bfloat16,
    device_map="cuda"
)

# Thunder compilation
model = thunder.jit(model)

# Forward pass to trigger the error
output = model(input_ids)

```

It results in the following error (message was shortened for clarity):

```
Traceback (most recent call last):
  File "<redacted>/main.py", line 26, in <module>
    output = model(input_ids)
<...>
  File "<redacted>/transformers/modeling_attn_mask_utils.py", line 158, in _make_causal_mask
    mask = torch.full((tgt_len, tgt_len), torch.finfo(dtype).min, device=device)
  File "<redacted>/thunder/core/interpreter.py", line 6069, in _call_dispatch
    opaque_result: Any = fn(*args_, **kwargs_)
TypeError: finfo(): argument 'type' (position 1) must be torch.dtype, not floating

```

**Comment by kshitij12345** [comment]
@mjmikulski I am unable to repro the error on latest main and the snippet works fine. IIRC, the error should be fixed with https://github.com/Lightning-AI/lightning-thunder/pull/759

**Comment by mjmikulski** [comment]
@kshitij12345 hmm, I installed `Thunder` following the instructions in README. Maybe the pip package was not updated since the fix was merged?

**Comment by kshitij12345** [comment]
I think the pip version is really old and not updated since March. For now, we should always install from main branch. We should update the README accordingly.

cc: @IvanYashchuk

**Comment by IvanYashchuk** [comment]
I agree with Kshiteej and will submit a patch to update README.

**Comment by kshitij12345** [comment]
Given that the README has been updated to recommend installation from main and as the above script passes on main, I think we should close the issue, wdyt @mjmikulski?
