### ISSUE TITLE
test_core_vs_torch_consistency_cross_entropy_torch_cuda_thunder.dtypes.bfloat16 failed

### ISSUE THREAD

**Issue by mruberry** [Lightning-AI/lightning-thunder#1338]
See https://dev.azure.com/Lightning-AI/lightning/_build/results?buildId=218036&view=logs&j=3f274fac-2e11-54ca-487e-194c91f3ae9f&t=7d03ab59-8b52-555c-a216-77e14d28deec&l=15075

```
FAILED thunder/tests/test_ops.py::test_core_vs_torch_consistency_cross_entropy_torch_cuda_thunder.dtypes.bfloat16 - AssertionError: Scalars are not close!

Expected 5.96875 but got 6.0625.
Absolute difference: 0.09375 (up to 0.01 allowed)
Relative difference: 0.015706806282722512 (up to 0.01 allowed)
```

cc @borda

**Comment by IvanYashchuk** [comment]
Repeating the test 10 times results in 0 errors and takes 1 minute. Probably it's an unfortunate random seed combined with bf16 numerical behavior. Usually, Thunder has a different order and a different number of upcasts and downcasts from/to bf16 when compared to eager execution.
```
pytest thunder/tests/test_ops.py::test_core_vs_torch_consistency_cross_entropy_torch_cuda_thunder.dtypes.bfloat16 --count=10
```
I'll run for 100 times for fun.
