### ISSUE TITLE
Upgrade nvFuser in CI

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#1372]
## 🚀 Feature

Please upgrade nvFuser to 0.2.22 or later.

### Motivation

We are [hitting bugs](https://github.com/Lightning-AI/lightning-thunder/pull/1340/checks?check_run_id=32239953960) that are fixed in more recent versions of nvFuser, and this is blocking #1340 at least.

### Additional context

The command you'd want to use to do this will depend on which version of torch and CUDA you are using.

* CUDA 12.4, torch 2.4: `python3 -m pip install --extra-index-url https://pypi.nvidia.com --pre nvfuser-cu124-torch24`
* CUDA 12.1, torch 2.3: `python3 -m pip install --extra-index-url https://pypi.nvidia.com --pre nvfuser-cu121-torch23`
* CUDA 12.4 nightly torch: `python3 -m pip install --extra-index-url https://pypi.nvidia.com --pre nvfuser-cu124`

**Comment by t-vi** [comment]
I'll take care of it.

**Comment by t-vi** [comment]
Note that the NVIDIA PyPI does not seem to have recent packages built against stable PyTorch, so there is little we can do without updates to the packages (torch25 might be interesting, too)...

e.g. https://pypi.nvidia.com/nvfuser-cu121-torch24/

**Comment by xwang233** [comment]
Sorry about the delay there. We decided to push nvfuser build against torch stable to pypi.org _twice a month_ (1st and 15th).

Nvfuser build against torch nightly will still be pushed _nightly_ to pypi.nvidia.com every day.

I'll trigger a build for nvfuser build against torch stable 2.5 now to unblock CI upgrades.

**Comment by xwang233** [comment]
Also, the nightly and stable builds now supports (python 3.10, and **3.12**) x (cuda 11.8, 12.1, and 12.4)

**Comment by jjsjann123** [comment]
> Nvfuser build against torch nightly will still be pushed _nightly_ to pypi.nvidia.com every day.

do you mind updating the installation instruction in TomF's comment at the top? (for build against stable torch from pypi.org)

**Comment by t-vi** [comment]
We currently take nvfuser from PyPI, but I don't seem to see recent updates, e.g in https://pypi.org/project/nvfuser-cu121-torch24/#history

**Comment by xwang233** [comment]
> We currently take nvfuser from PyPI, but I don't seem to see recent updates, e.g in https://pypi.org/project/nvfuser-cu121-torch24/#history

Builds against torch stable are ongoing and will be pushed to pypi.org in a few hours. Starting 11/1, builds against torch stable will be pushed twice a month to avoid delays in nvfuser features.

**Comment by tfogal** [comment]
> ... to avoid delays in nvfuser features.

Thank you, Xiao!

**Comment by xwang233** [comment]
![image](https://github.com/user-attachments/assets/bf191776-169e-46b8-9a55-bfbe25fcd4b2)

nvfuser builds against torch25 are uploaded to pypi.org

**Comment by t-vi** [comment]
@xwang233 Thank you. I'll bump the CI to pt 2.5.1. Do you have plans for building torch24, too? If not we need to bump the docs to use 2.5 as well.

**Comment by xwang233** [comment]
> Do you have plans for building torch24, too?

The automatic CI builds against stable is always for the latest torch stable release (`pip install torch`). If you need builds against old torch releases, we may be able to add those.
