### ISSUE TITLE
thunder vs torch.compile

### ISSUE THREAD

**Issue by deependujha** [Lightning-AI/lightning-thunder#1431]
Hi! I’m new to Deep Learning Compilers, but I’ve been exploring torch.compile and recently completed the `Lightning Thunder Sessions`. Here’s my current understanding:

**Thunder**: Traces the execution path and applies optimizations (like dead code elimination, fusion, etc.) before handing off to a backend like Triton, cuDNN, or Inductor for code generation. Thunder also allows for custom kernel creation, where developers can register their own kernels to be used by the backend.

**torch.compile**: This also seems to follow a similar process. torchdynamo handles tracing, AOTAutograd and PrimTorch take care of tracing the backward pass and operator simplification, torch.fx handles functional transformations, and torchinductor generates backend-optimized code using backends like Triton and cuDNN.

Given these similarities:

1. What exactly is the **difference between thunder and torch.compile**?

2. Is Thunder built to improve upon torch.compile, or does it aim to provide a different approach to optimization?

3. Are there specific **use cases where Thunder is expected to perform better than torch.compile**, or does it bring unique features or flexibility for certain types of optimizations?

Thanks for helping me get a better understanding of the space!

**Comment by t-vi** [comment]
We discuss the goals of Thunder and our understanding of what various compilers, including torch.compile, do in the earlier episodes of the [Thunder Sessions podcast](https://www.youtube.com/playlist?list=PLaMu-SDt_RB7ImARcTT_Wjypwx2vBIBen).

We love `torch.compile` and use it as a backend (and also have an optional path using it as a frontend). The PyTorch team is doing a great job there, they explain their design goals much better in the PyTorch conference talks than I could here.

We aim for `thunder.jit` to maximize usability, understandability, and extensibility, and this drives our design. One aspect here is that we want Thunder to be a thin framework, where you can also take parts that work best for you and maybe skip some others. Similarly, you can easily mix and match optimizations as you see fit.

The answer to 3 probably depends on your use-case and optimizations.
Thunder has, maybe, a more broad view as to what transformations it does to achieve it's goals - so we view some holistic transforms (e.g. write your model as FP, then quantize it with a Thunder transform) as part of what we do, I don't know if that is as much the case for other model compilation.
We are working on providing Thunder Recipes as a way to allow developers of optimizations to bundle them up for people interested more in "take a model and run it fast" than the more detailed optimzation. The [14th episode of the Thunder Sessions](https://www.youtube.com/watch?v=tNZk-i_rDW8&list=PLaMu-SDt_RB7ImARcTT_Wjypwx2vBIBen&index=14) has more on this.

I hope this clears some of the questions. I'm closing this issue as not actionable, we (@lantiga ) will update the readme soonish to clear things up, too.
