### ISSUE TITLE
ThunderFX: Interface UX

### ISSUE THREAD

**Issue by kiya00** [Lightning-AI/lightning-thunder#1529]
It would be nice if instead of having to write

<pre class="ql-syntax" spellcheck="false">backend = ThunderCompiler()
opt_foo1 = torch.compile(foo, backend=backend)
</pre><p> </p><p>We instead allowed practitioners to write</p><p> </p>

<pre class="ql-syntax" spellcheck="false">from thunder import thunderfx

tfoo = thunderfx(foo)
</pre><p> </p><p>Notebooks like this are a good opportunity to identify areas for improvement in our UX like this. We can create the thunderfx function so it accepts <code>**kwargs</code> to pass to the torch.compile call, too. </p><p> </p><p>It'd be great to see a PR changing this so we can update this doc. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/Lightning-AI/lightning-thunder/pull/1524/discussion/#comment-1873705406'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='3'/>

_Originally posted by @mruberry in https://github.com/Lightning-AI/lightning-thunder/pull/1524#discussion_r1873705406_
            

cc @borda

**Comment by mruberry** [comment]
Note from triage today: we should follow-up with thinking about how we explain the `thunderfx` vs. `thunder.jit` entrypoints. 

I filed https://github.com/Lightning-AI/lightning-thunder/issues/1532 to track that issue, which we can separate from these proposed changes.

**Comment by mruberry** [comment]
> As @mruberry has suggested, we can wrap it like this, WDYT @t-vi @IvanYashchuk
> 
> ```
> def thunderfx(fn: Callable, thunder_options: dict, **kwargs):
>     backend = ThunderCompiler(thunder_options)
>     return torch.compile(fn, **kwargs)
> ```
> 
> `thunder_options` corresponds to the constructor options of `ThunderCompiler`

This is a good idea. What about the following tweak?

```
def thunderfx(fn: Callable, /, **kwargs):
  # Separate torch.compile kwargs from thunder kwargs here
  # To separate them, we could do something like this:
  
  torch_compile_kwarg_names = inspect.getfullargspec(torch.compile).kwonlyargs

  torch_compile_options = {k:v for k:v in kwargs if k in torch_compile_kwarg_names}
  thunder_options = {k:v for k:v in kwargs if k not in torch_compile_kwarg_names}

  # Change ThunderCompiler to take thunder_options and torch_compile_options separately and as dicts
  backend = ThunderCompiler(thunder_options, torch_compile_options)
  return torch.compile(fn, backend=backend, **torch_compile_options)
```

That would let all arguments be specified like regular kwargs, and I think it would slightly cleanup the ThunderCompiler dunder init function, too. This approach might have some issues in the future because:

1) torch.compile could start accepting kwargs, so we'd have to send extra keywords to both torch.compile and thunder and hope they don't overlap
2) torch.compile could add new keyword arguments that overlap with thunder keyword arguments, so we'd have to detect if an argument applies to both and send it to both as appropriate or change the UX again

I think these are OK problems to have, and we can address them if they come up in the future. 

One refinement of this scheme would be to explicitly list known kwargs in the signature, so the signature could include kwargs for "fullgraph" and thunder options, for example. That would make the signature more readable if anyone looked at it. Then the ThunderCompiler dunder init could also accept some kwargs explicitly, which might be clearer.

**Comment by kshitij12345** [comment]
One thing to note is that `ThunderCompiler` object itself holds the Dynamo Subgraphs and other details useful for debugging in SubgraphInfo. So, when someone wants to debug or inspect the splits or grab the trace for the thunder function/s for that Subgraph, they currently require access to the `ThunderCompiler` object.

So the UX should consider this object as well.

Few options I can think of -
1. Return a future-like object which will be populated with subgraph info details - so the signature can become something like `thunderfx(fn, /, **kwargs) -> tuple[Callable, SubgraphInfoFutureObject]`. This object is not ready till the first call to the returned `Callable`.
2. Similar to what we have to grab traces (`thunder.last_traces`), we can attach the SubgraphInfo to the Callable returned from `thunderfx` function and then have a helper function `get_subgraph_info` which will pull this data if available.

Irrespective of the approach, I think my main point is to make sure that this information is still easily accessible.

https://github.com/Lightning-AI/lightning-thunder/blob/087637f0e443ae08824f23940f3e02dfcf8e02fc/thunder/dynamo/utils.py#L103-L122

**Comment by kiya00** [comment]
Yes, `ThunderCompiler` has `SubgraphInfo` attribute and `save_reproducer_to_folder` method so far to provide some debugging information. I was trying to simply add a `_backend` attribute (#1535 ) to the returned compiled callable so that the advanced user can have full access to `ThunderCompiler`. Or maybe we want a bunch of interfaces instead? like `get_subgraph_infos`, `save_reproducer`

Also I noticed in some cases users use it like:
```
from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer, get_scheduler
model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.bfloat16)
be = thunder.dynamo.ThunderCompiler(transforms=xforms)
model.compile(backend=be)
```
and it seems in this case it's easier to use `ThunderCompiler`

**Comment by mruberry** [comment]
> Yes, `ThunderCompiler` has `SubgraphInfo` attribute and `save_reproducer_to_folder` method so far to provide some debugging information. I was trying to simply add a `_backend` attribute (#1535 ) to the returned compiled callable so that the advanced user can have full access to `ThunderCompiler`. Or maybe we want a bunch of interfaces instead? like `get_subgraph_infos`, `save_reproducer`
> 
> Also I noticed in some cases users use it like:
> 
> ```
> from transformers import AutoConfig, AutoModelForCausalLM, AutoTokenizer, get_scheduler
> model = AutoModelForCausalLM.from_config(config, torch_dtype=torch.bfloat16)
> be = thunder.dynamo.ThunderCompiler(transforms=xforms)
> model.compile(backend=be)
> ```
> 
> and it seems in this case it's easier to use `ThunderCompiler`

Adding attributes to the returned callable, or creating new methods to access this information, both sound like great ideas that we can follow-up with in the future.

It would also be nice to consider how those functions compare to the existing functions for accessing thunder.jit data, like:

https://github.com/Lightning-AI/lightning-thunder/blob/9de543417260bd32740e2d7bd0763a5871fdee5c/thunder/__init__.py#L827

But we can also work on aligning these options later, too
