### ISSUE TITLE
ad_hoc_executor: the `torch.autograd.Function` outputs a wrong bwd trace when the input is a cuda tensor.

### ISSUE THREAD

**Issue by kiya00** [Lightning-AI/lightning-thunder#1568]
*Note*: If you have a model or program that is not supported yet but should be, please use the program coverage template.

## 🐛 Bug

the `torch.autograd.Function` gives wrong bwd trace when the input is cuda tensor.

### To Reproduce

```
import torch
import thunder

x = torch.ones(2, device="cuda", requires_grad=True)
x_cpu = torch.ones(2, requires_grad=True)

class Sin(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        ctx.save_for_backward(x)
        return torch.sin(x)

    @staticmethod
    def backward(ctx, g):
        (x,) = ctx.saved_tensors
        return g * torch.cos(x) * 200

def func(x):
    return Sin.apply(x)

cfunc = thunder.jit(func)
# actual = cfunc(x)
actual = cfunc(x_cpu)
print(thunder.last_backward_traces(cfunc)[-1])
```

the backward trace when using cpu input (correct):
```
@torch.no_grad()
@no_autocast
def backward_fn(saved_for_backward, cotangents):
  # saved_for_backward: "Collection"
  # cotangents: "Collection"
  C0, _, = saved_for_backward
  clear_mutable_collection(saved_for_backward)
  del saved_for_backward
  t0, = cotangents
  clear_mutable_collection(cotangents)
  del cotangents
  x, = C0
  clear_mutable_collection(C0)
  del C0
  t7 = torch.cos(x)  # t7: "cpu f32[2]"
    # t7 = ltorch.cos(x)  # t7: "cpu f32[2]"
      # t7 = prims.cos(x)  # t7: "cpu f32[2]"
  del x
  t8 = torch.mul(t0, t7)  # t8: "cpu f32[2]"
    # t8 = ltorch.mul(t0, t7)  # t8: "cpu f32[2]"
      # t8 = prims.mul(t0, t7)  # t8: "cpu f32[2]"
  del t0, t7
  t9 = torch.mul(t8, 200)  # t9: "cpu f32[2]"
    # t9 = ltorch.mul(t8, 200)  # t9: "cpu f32[2]"
      # t9 = prims.mul(t8, 200.0)  # t9: "cpu f32[2]"
  del t8
  return (t9,)
```
the backward trace when using cuda input (there's no multiply 200):
```
@torch.no_grad()
@no_autocast
def backward_fn(saved_for_backward, cotangents):
  # saved_for_backward: "Collection"
  # cotangents: "Collection"
  C0, _, = saved_for_backward
  clear_mutable_collection(saved_for_backward)
  del saved_for_backward
  t0, = cotangents
  clear_mutable_collection(cotangents)
  del cotangents
  x, = C0
  clear_mutable_collection(C0)
  del C0
  [t8] = nvFusion0(x, t0)
    # t7 = prims.cos(x)  # t7: "cuda:0 f32[2]"
    # t8 = prims.mul(t0, t7)  # t8: "cuda:0 f32[2]"
  del x, t0
  return (t8,)
```
The reason is related to the executor order(?), 
https://github.com/Lightning-AI/lightning-thunder/blob/eff35942f52156345629a04182564efe9e209782/thunder/core/transforms.py#L2763
https://github.com/Lightning-AI/lightning-thunder/blob/eff35942f52156345629a04182564efe9e209782/thunder/core/transforms.py#L1470-L1485
cuda tensor uses nvfuser so it breaks in L1481, the `ad_hoc_executor` is not used, so it goes to the `decomposed_fn_aug_fwd_rule`

Also if I specify the `executors=[thunder.pytorch_executor]`, there is no `ad_hoc_executor`, the above case outputs the wrong bwd trace when input is cpu tensor. 

cc @apaz-cli
cc: @IvanYashchuk @t-vi  it can be related to the executor order

**Comment by crcrpar** [comment]
Does the same script work if we only use torch executor?

**Comment by t-vi** [comment]
Thank you for the execellent repro @kiya00 !

This is because the autodiff prefers derivative using subsymbol decomposition in earlier executors to later executors.
The adhoc executor should go first, I'll send a patch to fix.
