### ISSUE TITLE
Implement `nan_to_num`

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#176]
## 🚀 Feature

Implement [Tensor.nan_to_num](https://pytorch.org/docs/stable/generated/torch.nan_to_num.html#torch-nan-to-num)

### Motivation

NeMo [text-to-image model](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/text_to_image/imagen/imagen_training.py).

### Additional context

Note that the model actually uses the in-place `nan_to_num_` variant, but it's possible that we can work with the NeMo team to translate this to the out-of-place version for the near term.

**Comment by k223kim** [comment]
Hi Team, would it be ok for me to take this issue?

I am thinking of adding something like the following in `torch/__init__.py`.
```python
@torchsymbol(torch.nan_to_num)
def nan_to_num(...)
```
Let me know if I can get assigned to this issue :) Appreciate your help!

**Comment by k223kim** [comment]
As I look into this more, I think `torch.iinfo` has to be implemented in thunder. As I am referring to PyTorch, I am not certain how this can be added thunder. Can anyone provide me some suggestions?

**Comment by k223kim** [comment]
Hi @mruberry! Just wondering if you can provide me some guidance regarding `torch.finfo().max` and `torch.finfo().min` implementation for `nan_to_num`.
Here is the current implementation that I have for `nan_to_num`:
```python
@torchsymbol(torch.nan_to_num)
def nan_to_num(a: TensorLike, nan: None | Number = 0.0, posinf: None | Number = None, neginf: None | Number = None, /, out: None | TensorLike = None):
    if dtypes.is_boolean_dtype(a.dtype) or dtypes.is_integer_dtype(a.dtype):
        # do we need this?
        return a.clone() # does thunder support clone?

    if nan is None:
        nan = 0.0
    
    if posinf is None:
        posinf = torch.finfo(a.dtype).max
        # thunder version of finfo.max is needed ... not sure how

    if neginf is None:
        neginf = torch.finfo(a.dtype).min
        # thunder version of finfo.min is needed ... not sure how

    result = where(a != a, nan, a)
    result = where(a == -float("inf"), neginf, result)
    result = where(a == float("inf"), posinf, result)
    return a
```
I can create draft PR if that would be easier for you to take a quick look! Thanks for your time :)

Afterwards, I will add test cases and submit a PR!

Best,
Kaeun
