### ISSUE TITLE
Implement `Tensor.type`

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#177]
## 🚀 Feature

Implement [Tensor.type](https://pytorch.org/docs/stable/generated/torch.Tensor.type.html#torch.Tensor.type)

### Motivation

NeMo [text-to-image model](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/text_to_image/imagen/imagen_training.py).

cc @tfogal

**Comment by k223kim** [comment]
Hi Team! I have made a rough draft of the implementation of `Tensor.type`. I was not sure how to implement `non_blocking` at the moment. As per [this description](https://arc.net/l/quote/fiuqkpbv), it states the following:

>  If True, and the source is in pinned memory and destination is on the GPU or vice versa, the copy is performed asynchronously with respect to the host. Otherwise, the argument has no effect.

How do I know the source and destination from the input arguments of `Tensor.type`?

**Comment by t-vi** [comment]
@tfogal It's cool that we want to support it, but in terms of good style, NeMo should really be using `.to` instead, which is the much more standard way to do what is does.

**Comment by tfogal** [comment]
triage team: let's figure out how to guide Kaeun here.

@t-vi ack. need to figure out where these are coming from (could be megatron core, for example) before I can track on GitHub, but I added it to my personal list.
