### ISSUE TITLE
Refactor bucketing of AllReduce to be applied to a generic trace

### ISSUE THREAD

**Issue by IvanYashchuk** [Lightning-AI/lightning-thunder#184]
## 🚀 Feature

Today bucketing of AllReduce operation is done when the following conditions are met:
* `disable_torch_autograd` is set to False
https://github.com/Lightning-AI/lightning-thunder/blob/139cc2246b87f3e58d80b13897286a61d55826d8/thunder/__init__.py#L328
* `compile_data.fn.use_ddp` is set to True
https://github.com/Lightning-AI/lightning-thunder/blob/139cc2246b87f3e58d80b13897286a61d55826d8/thunder/executors/torch_autograd.py#L280-L283

We need to move the bucketing transformation out of the "torch autograd" code path to be applied in the generic thunder.jit pipeline with no information about "forward" or "backward".

This transformation could be placed to happen before "transform_for_execution" as part of the "additional_transforms":
https://github.com/Lightning-AI/lightning-thunder/blob/139cc2246b87f3e58d80b13897286a61d55826d8/thunder/__init__.py#L608-L610

or as the first step inside "transform_for_execution".

Currently, in the torch_autograd.py file, the allreduce bucketing transform is placed right before the "transform_for_execution":
https://github.com/Lightning-AI/lightning-thunder/blob/139cc2246b87f3e58d80b13897286a61d55826d8/thunder/executors/torch_autograd.py#L283-L292

cc @carmocca @awaelchli @crcrpar

**Comment by crcrpar** [comment]
> This transformation could be placed to happen before "transform_for_execution" as part of the "additional_transforms":

I'm not quite sure how this can be achieved other than removing the check of https://github.com/Lightning-AI/lightning-thunder/blob/139cc2246b87f3e58d80b13897286a61d55826d8/thunder/__init__.py#L580-L601

> or as the first step inside "transform_for_execution".

this might be a bit easier than the other approach.
