### ISSUE TITLE
Add a lookaside for `torch.compile` and investigate interpreter failure

### ISSUE THREAD

**Issue by apaz-cli** [Lightning-AI/lightning-thunder#186]
Earlier, there was confusion about how to use `torch.compile` with thunder. And so, someone tried to jit a model with a call to `torch.compile` in it. This did not work, and the result is still an interpreter stack trace spew. Ideally it should fail more gracefully. 

Reproduce with the following:
```py
import torch
import thunder

def model(a, b, c):
  return a @ b + c

def jit_me(x):
  cfn = torch.compile(model)
  return cfn(x)

jcfn = thunder.jit(jit_me)

x = torch.randn(2, 2)
y = torch.randn(2, 2)
z = torch.randn(2, 2)
res = jcfn(x, y, z)
```

Two things should be done. First, to provide a better error message, you can add a lookaside for `torch.compile`. The convention is to use `do_raise()` for exceptions thrown from inside the code, and `raise` for interpreter errors. This is an interpreter error, so you would just `raise` an exception with an informative error message about how to use the full `torch.compile` executor. Which is still in the works. So, a placeholder would suffice, at least until #140 is merged.

Second, it would be nice to understand what the stack trace means. If there's a bug in the interpreter, we would like to know about it. We know that `torch.compile` does plenty of trickery that we can't model. But it would be nice to know exactly where we're getting tripped up, and why.

cc @apaz-cli

**Comment by Rana-KV** [comment]
Hi @apaz-cli , I'm interested to work this issue.

**Comment by t-vi** [comment]
Hi Rana-KV, I'm glad to hear that. So the lookaside would be added to the general jit in thunder.core.jit_ext as a function decorated with
```
@general_jit_lookaside(torch.compile)
```
and returning `do_raise(NotImplementedError("<some message>"))`.

This combined with a test in thunder.test.test_jit_general should do the trick basic.

The next step could be to figure out something to detect already-compiled functions, but that is a different issue.

**Comment by Rana-KV** [comment]
Thank you @t-vi, I had a much clear picture with the information you provided. I have made the necessary changes and created a PR. 
Should I also create testcase and update documents? I saw it was a small change and didn't do it.
