### ISSUE TITLE
benchmarking — create a notebook showing how to work with the single gpu benchmarks

### ISSUE THREAD

**Issue by mruberry** [Lightning-AI/lightning-thunder#205]
The notebook should

- show how to understand what the benchmark's options are
- show how to programmatically run the benchmark
- show how to create the callable that the benchmark is invoking
- show how to acquire the input generator the benchmark is using to create the inputs to the callable

This way practitioners will be able to run the benchmark callable in their own contexts, which should support profiling.

fyi @kevinstephano — is this what you were thinking of when talking about extracting a callable from a benchmark?

cc @borda @apaz-cli @crcrpar

**Comment by kevinstephano** [comment]
This sounds good!

This might already be in mind with these bullet points but it would be helpful to show explicitly how to:
* Show the trace
* Execute specific fusions
* Dump the debug for specific fusions

**Comment by riccardofelluga** [comment]
Regarding the debug for a specific fusion I've created #387. If that goes through I will show in this notebook how to use that information to dump it for specific fusions so that then it's just a matter of reading the output and creating the repro script
