### ISSUE TITLE
Benchmarking suite that runs scripts

### ISSUE THREAD

**Issue by riccardofelluga** [Lightning-AI/lightning-thunder#224]
As part of the automated benchmarking I would like the benchmarks to automatically report metrics and save them for comparison.

cc @crcrpar

**Comment by IvanYashchuk** [comment]
What metrics are you interested in and what is currently missing from our current benchmarks? How does https://github.com/Lightning-AI/lightning-thunder/pull/1008 fulfils your request?

**Comment by riccardofelluga** [comment]
At the moment the current benchmark scripts do not miss any major metric. #1008 allows for saving these metrics over time in a asv format.
