### ISSUE TITLE
cuDNN executor leaks to some other benchmarks if run first in the list

### ISSUE THREAD

**Issue by IvanYashchuk** [Lightning-AI/lightning-thunder#230]
## 🐛 Bug

All 3 grad_executors with "thunder" run cudnn, even though only one of them includes it.
The below command runs all grad_exectuors:
```
pytest /opt/pytorch/lightning-thunder/thunder/benchmarks/targets.py -k "test_llama2_7b_sdpa_grad" -vvv
```
and outputs:
```
 ---------------------------------------------------------------------------------------------------- benchmark: 5 tests ---------------------------------------------------------------------------------------------------
Name (time in ms)                                               Min                Max               Mean            StdDev             Median               IQR            Outliers      OPS            Rounds  Iterations
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
test_llama2_7b_sdpa_grad[thunder+cudnn]                     24.0029 (1.0)      26.4341 (1.08)     24.1997 (1.0)      0.4278 (5.09)     24.0555 (1.0)      0.1321 (1.17)          2;3  41.3229 (1.0)          40           1
test_llama2_7b_sdpa_grad[thunder+nvfuser+torch.compile]     24.0188 (1.00)     24.4665 (1.0)      24.2119 (1.00)     0.0840 (1.0)      24.1968 (1.01)     0.1127 (1.0)          11;1  41.3021 (1.00)         40           1
test_llama2_7b_sdpa_grad[thunder]                           24.0243 (1.00)     27.0159 (1.10)     24.2562 (1.00)     0.4582 (5.46)     24.1841 (1.01)     0.1934 (1.72)          1;1  41.2266 (1.00)         40           1
test_llama2_7b_sdpa_grad[torch]                             29.6719 (1.24)     30.4860 (1.25)     29.9658 (1.24)     0.1559 (1.86)     29.9799 (1.25)     0.2149 (1.91)          7;1  33.3713 (0.81)         40           1
test_llama2_7b_sdpa_grad[torch.compile]                     29.7168 (1.24)     30.6249 (1.25)     29.9615 (1.24)     0.2477 (2.95)     29.9007 (1.24)     0.4102 (3.64)          4;0  33.3762 (0.81)         40           1
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```
But if you run of them in isolation:
```
pytest /opt/pytorch/lightning-thunder/thunder/benchmarks/targets.py -k "test_llama2_7b_sdpa_grad[thunder]" -vvv
it outputs:
------------------------------------------------------ benchmark: 1 tests -----------------------------------------------------
Name (time in ms)                         Min      Max     Mean  StdDev   Median     IQR  Outliers      OPS  Rounds  Iterations
-------------------------------------------------------------------------------------------------------------------------------
test_llama2_7b_sdpa_grad[thunder]     29.7061  30.5890  29.9495  0.2633  29.7619  0.4166       4;0  33.3896      40           1
------------------------------------------------------------------------------------------------------------------------------- 
```
Notice the difference in times.

^ Thank you @vedaanta-nvidia for noticing the problem!

Running with Nsight Systems confirms that cuDNN executor is being used in other benchmarks when it's not supposed to.

cc @crcrpar

**Comment by IvanYashchuk** [comment]
The problem was introduced in f37ac34399c8f039637b527a79064d106abb4bc2.

@kshitij12345,  could you please take a look at what's going on and fix the problem?

**Comment by kshitij12345** [comment]
**Findings**:

For the first call `thunder.jit(fn, executors=[cudnn_ex])`, in `make_aug_forward_and_backward` we get the gradfn using `_get_gradfn` for symbol `torch.nn.functional.scaled_dot_product_attention`. Then the generated split forward and backward is cached with key generated from Symbol, args and kwargs (but not the executor whose gradfn we chose).

Ref to where the cache is in `make_aug_forward_and_backward`:
https://github.com/Lightning-AI/lightning-thunder/blob/6cd19c4d7f23b635513cbc029c7eea6652708f65/thunder/core/vjp_utils.py#L52-L62

In the next call `jfn = thunder.jit(fn)`, for the same symbol `torch.nn.functional.scaled_dot_product_attention`, we hit the cache (even though the gradfn came from `sdpa` executor). Hence we end up using the `cudnn` executor even when it is not in the executors list.

**Potential Solution**:
I think `_get_gradfn` should also return the executor (or None if choosing the default transform) whose grad implementation was chosen which should then be used as part of the key for cache in `make_aug_forward_and_backward`.

https://github.com/Lightning-AI/lightning-thunder/blob/6cd19c4d7f23b635513cbc029c7eea6652708f65/thunder/core/transforms.py#L1267-L1281

**Comment by IvanYashchuk** [comment]
Thanks for digging into this! I agree with you that updating the cache key here is the right solution.
