### ISSUE TITLE
`torch.Tensor.numel` method : Don't know how to interpret a callable with type <class 'int'>

### ISSUE THREAD

**Issue by kshitij12345** [Lightning-AI/lightning-thunder#240]
It is because `TensorProxy` models `numel` as a property but it is a method in a PyTorch and numpy doesn't have `numel` but has `size`. I think this `numel` should be modelled based on current language context to be a method for PyTorch context and error in case of Numpy context.

```python
import thunder
import torch

import thunder.examine

def foo(x):
    return x.numel()

# thunder.examine.examine(foo, torch.rand(3, 3))
thunder.jit(foo)(torch.rand(3, 3))

```

Error:
```
 File "/home/kkalambarkar/lightning-thunder/thunder/core/interpreter.py", line 6664, in fn_
    raise InterpreterError(msg) from e
thunder.core.interpreter.InterpreterError: Encountered exception NotImplementedError: Don't know how to interpret a callable with type <class 'int'> without a __call__ method while tracing <function foo at 0x7f339910fd90>:
```

cc @apaz-cli

**Comment by nikitaved** [comment]
Yeah, I did hit this when working with transforms. Looks like another great first issue :)

**Comment by mruberry** [comment]
Thank you for filing this issue, @kshitij12345

This seems a little tricky. There are some things we would like to always be properties of TensorProxy objects, even when they're not in a language context, and the number of elements in a tensor could be one of them. 

I like your proposal of modeling the property vs. function correctly, @kshitij12345. If we want to support numel when outside of any language context, maybe we should add the ability to fallback to a default implementation, too?

**Comment by k223kim** [comment]
Hello Team ⚡️! I am wondering if it would be ok for me to work on this issue :)
I guess a quick work around is to add the `numel` method to `torch/__init__.py` and remove the `numel` property in `TensorProxy`. However, I as per @mruberry 's comment, I believe there is a better way to approach this issue. Can someone provide me some additional guidance as in what exactly we want?

**Comment by mruberry** [comment]
> Hello Team ⚡️! I am wondering if it would be ok for me to work on this issue :)

Of course it is!

> I guess a quick work around is to add the `numel` method to `torch/__init__.py` and remove the `numel` property in `TensorProxy`. However, I as per @mruberry 's comment, I believe there is a better way to approach this issue. Can someone provide me some additional guidance as in what exactly we want? (cc. @kshitij12345 )

Absolutely. I think the steps are:

- Add the `numel` function to the torch language definition
- Remove the `numel` property from the `TensorProxy` class (let's keep it on the `FutureTensorProxy` class for now)
- Update `resolve_method` to return `None` when `get_langctx()` raises a `LookupError`

https://github.com/Lightning-AI/lightning-thunder/blob/de612bd54224f1f9ee6b0bc60f9ed152693903f8/thunder/core/langctxs.py#L66

- Update the `__getattr__` method on the `TensorProxy` class to check for the resolved method or value being `None`:

https://github.com/Lightning-AI/lightning-thunder/blob/de612bd54224f1f9ee6b0bc60f9ed152693903f8/thunder/core/proxies.py#L1234

- Implement a `get_default_attr` method on `TensorProxy` that accepts `attr` and is a fallback for when `method_or_value` is `None`. It should attempt to populate `method_or_value`, like this:

```
method_or_value: None | Callable | Any = resolve_method(attr, self)

if method_or_value is None:
  method_or_value = self.get_default_attr(attr)

baseutils.check(method_or_value is not None, lambda: f"Unknown attribute {attr}", exception_type=AttributeError)
```

- `get_default_attr` should have a simple implementation for now:

```
def get_default_attr(self, attr: str, /) -> None | Any:
  if attr == "numel":
   return self._numel

  return None
```

- Write a test that `t.numel()` works as expected, that `torch.numel(t)` works as expected, and that creating a `TensorProxy` and accessing `tp.numel` works as expected (outside of a thunder program, so there is no language context). The test can go in `test_core.py`

Does that make sense, @k223kim?

**Comment by k223kim** [comment]
Hi @mruberry ! Thanks again for the warm welcome with a detailed response. I am currently trying to understand each step in more depth, and so far, I think it does make sense! Will reach out once I have questions. Much appreciated!

**Comment by mruberry** [comment]
> Hi @mruberry! Just wondering, is there a way to change/switch/remove language context? In `torch/__init__.py`, `def group_norm`, when it calls `numel`, it's language context seems to be PyTorch. However, to fallback to the TensorProxy's default attribute, it has to be None. I was working on this for a while and wondering if you can give me a hint :)

Yes there is! But we probably just want to update uses of `.numel` in torch language contexts to properly call `.numel()`. The language context can be explicitly set a few ways, but the most straightforward is probably by using the language context decorator here:

https://github.com/Lightning-AI/lightning-thunder/blob/3a2b27e9b38e639133913c42c03acdf0e136ec4f/thunder/core/langctxs.py#L102

We can see this decorator being applied by other decorators, like for this one in the core language:

https://github.com/Lightning-AI/lightning-thunder/blob/3a2b27e9b38e639133913c42c03acdf0e136ec4f/thunder/clang/__init__.py#L39

lines like this one, where `.numel` is accessed as an attribute equal to a number:

https://github.com/Lightning-AI/lightning-thunder/blob/3a2b27e9b38e639133913c42c03acdf0e136ec4f/thunder/clang/__init__.py#L925

should continue working in the clang language context after this change, but the same line will no longer work as expected in the torch language context, where the code has to use `.numel()`

**Comment by k223kim** [comment]
> Yes there is! But we probably just want to update uses of .numel in torch language contexts to properly call .numel().

I didn't think that was an option. This makes much sense. Thank you so much! (+ Also, thanks for showing me how language context is set explicitly! 🚀)
