### ISSUE TITLE
cuDNN SDPA executor has CPU overhead

### ISSUE THREAD

**Issue by parthmannan** [Lightning-AI/lightning-thunder#241]
## 🐛 Bug

LLaMa2 7B FSDP ZeRO2 performance
Microbatch=1, Global batch=8 on 8xH100

```
torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --compile=thunder_inductor_cudnn --distributed_mode=fsdp --nsys_enabled=False --micro_batch_size=1 --global_batch_size=8 --model_name=Llama-2-7b-hf
thunder_inductor: 406.34 ms/iter
```
```
torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --compile=thunder_inductor_cudnn --distributed_mode=fsdp --nsys_enabled=False --micro_batch_size=1 --global_batch_size=8 --model_name=Llama-2-7b-hf
thunder_inductor_cudnn: 637.73 ms/iter
```

To dig deeper into why the addition of cuDNN SDPA executor leads to worse performance, one can use Nsight systems profiler as follows - 

```
Thunder+Inductor
nsys profile -w true -t cublas,cuda,nvtx,osrt -s cpu -c cudaProfilerApi -o llama2_7b_thunder-inductor torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --compile=thunder_inductor --distributed_mode=fsdp --nsys_enabled=True --micro_batch_size=1 --global_batch_size=8 --model_name=Llama-2-7b-hf
```
Here's what the profile looks like. The timeline is tighly packed with kernels.

<img width="1578" alt="Screenshot 2024-04-21 at 3 55 12 PM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/843ac14a-3009-458b-ae56-ae5dab869780">

```
Thunder+Inductor+cuDNN
nsys profile -w true -t cublas,cuda,nvtx,osrt -s cpu -c cudaProfilerApi -o llama2_7b_thunder-inductor-cudnn torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --compile=thunder_inductor_cudnn --distributed_mode=fsdp --nsys_enabled=True --micro_batch_size=1 --global_batch_size=8 --model_name=Llama-2-7b-hf
```
Here's what this profile looks like. Note the large gaps in the execution timeline marked by the red boxes.

<img width="1578" alt="Screenshot 2024-04-21 at 3 55 42 PM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/c7cf5999-b805-45c5-b698-d9afc637ef0b">

Let's zoom into one of these gaps. One can see that it's because the cuDNN backward pass has a long lag time before the kernel is launched. There is some overhead on the CPU where no kernels are launched for a long time and that makes the GPU idle.
cuDNN SDPA is significantly faster than FlashAttention/Torch SDPA on GPU execution time but the overhead in launching the kernel in the backward pass is leading to a slowdown.

<img width="1583" alt="Screenshot 2024-04-21 at 3 59 55 PM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/da2fcf45-0519-4576-9273-484461df5af3">

Please ping me for the profiles and I can provide the raw .nsys-rep files as well.

CC - @vedaanta-nvidia @Anerudhan

**Comment by mruberry** [comment]
triage review:

- assigning to @ptrblck to reassign

**Comment by ptrblck** [comment]
CC @eqy as we were seeing potentially similar issues in PyTorch.

**Comment by eqy** [comment]
I'm interested in whether this is comparable to what we see in PyTorch (which uses cuDNN's C++ frontend API). Do you have a sense for what the absolute size of the gap is in microseconds? From simple profiling in PyTorch it looks to be about 100-200us from the start of the nvtx range (wrapped around an `out.backward` call) to the first cuDNN kernel starting. This gap seem to be comparable to native PyTorch Flash Attention.

**Comment by parthmannan** [comment]
@eqy The gap in Thunder seems much larger than that. 

The gap between kernel launches seem to be on the order of 20ms.
![Screenshot 2024-04-24 at 1 29 31 PM](https://github.com/Lightning-AI/lightning-thunder/assets/38387286/0d0410c1-375f-4379-b02f-48bba1d1f1d9)

The resulting gap between kernel execution is around 10ms.
![Screenshot 2024-04-24 at 1 29 54 PM](https://github.com/Lightning-AI/lightning-thunder/assets/38387286/65390fb1-ce72-4268-91b6-33b82553d32e)

@vedaanta-nvidia is looking into the CPU launch overhead here.

**Comment by vedaanta-nvidia** [comment]
I profiled various stages in graph execution both in thunder and in cudnn internals.
The mostly costly part turned out to be cudnn's graph validation. #271 caches it too now.

After PR #271:
LLaMa2 7B FSDP ZeRO2 performance
Microbatch=1, Global batch=8 on 8xH100
thunder_inductor: 406.34 ms/iter
thunder_inductor_cudnn: 388.13 ms/iter

Current cpu launch overhead ranges from 350 us to 1000 us in an iteration. Will be looking further to get it within 500 us.
