### ISSUE TITLE
Add sanity check for primitive inplace copy operator

### ISSUE THREAD

**Issue by kiya00** [Lightning-AI/lightning-thunder#265]
## 🚀 Feature

Add a sanity check to ensure the `copy_to` argument of `prims.copy_` is not used as input for any of its subsequent operators

### Motivation

Nvfuser's `fd.add_output(output, input)` API has the rule "do not use the input after it has been updated". We need the same sanity check for `prims.copy_(copy_from, copy_to)`.

cc: @IvanYashchuk @jjsjann123

**Comment by jjsjann123** [comment]
wondering if this is part of #145 , or just a simple patch to catch the obvious issues?

**Comment by kiya00** [comment]
> wondering if this is part of #145 , or just a simple patch to catch the obvious issues?

I think that's a simple patch and could be removed when the full inplace analysis is ready
