### ISSUE TITLE
Implement TensorBase.gather

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#267]
### 🚀 Feature

Implement [`TensorBase.gather`](https://pytorch.org/docs/stable/generated/torch.gather.html)

### Motivation

NeMo [Stable Diffusion](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/text_to_image/stable_diffusion/sd_train.py)

cc @apaz-cli @tfogal

**Comment by mruberry** [comment]
triage review — @rdspring1 is this issue out of date, or does the method variant of `gather` need to be implemented, too?

**Comment by rdspring1** [comment]
`gather` is implemented at https://github.com/Lightning-AI/lightning-thunder/blob/main/thunder/torch/__init__.py#L1988.
Should I enable the `is_method` option for `gather` and `scatter_add`?

**Comment by mruberry** [comment]
> `gather` is implemented at [`main`/thunder/torch/__init__.py#L1988](https://github.com/Lightning-AI/lightning-thunder/blob/main/thunder/torch/__init__.py?rgh-link-date=2024-05-06T20%3A28%3A19Z#L1988). Should I enable the `is_method` option for `gather` and `scatter_add`?

That'd be great!
