### ISSUE TITLE
Implement TensorBase.long

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#268]
🚀 Feature

Implement [`TensorBase.long`](https://pytorch.org/docs/stable/generated/torch.Tensor.long.html)

### Motivation

NeMo [Stable Diffusion](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/text_to_image/stable_diffusion/sd_train.py)

cc @tfogal

**Comment by tfogal** [comment]
triage team: AFAICT none of NeMo's use cases for this use the `memory_format` parameter. maybe we could have a half-implementation of this that errors out when this parameter is used?
