### ISSUE TITLE
torch.unflatten not supported by thunder.jit

### ISSUE THREAD

**Issue by Fuzzkatt** [Lightning-AI/lightning-thunder#288]
torch.unflatten is not supported by thunder.jit. However, we see that torch.reshape is supported by thunder.jit and we can rewrite torch.unflatten with torch.reshape to accomplish the same final result. 

Minimal repro:

```
import torch
import thunder
from thunder.examine import examine

a = torch.randn(100, 128*3, device='cuda')

final_shape = list(a.shape)
final_shape[-1] = 3
final_shape.append(128)

# works
examine(torch.reshape, *(a, final_shape))

# fails
examine(torch.unflatten, *(a, -1, (3, 128)))
```

cc @apaz-cli

**Comment by mruberry** [comment]
triage review — let's add unflatten!
