### ISSUE TITLE
Implement _VariableFunctionsClass.baddbmm of torch

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#326]
## 🚀 Feature

Implement [`torch.baddbmm`](https://pytorch.org/docs/stable/generated/torch.baddbmm.html)

### Motivation

NeMo [Vision Transformer](https://github.com/NVIDIA/NeMo/blob/main/examples/vision/vision_transformer/megatron_vit_classification_pretrain.py)

cc @apaz-cli @tfogal

**Comment by tfogal** [comment]
FWIW it looks like [NeMo always sets `beta` to `0.0`](https://github.com/NVIDIA/NeMo/blob/8e65042d15062ce3fbe639f9d428c639510d894c/nemo/collections/nlp/modules/common/megatron/attention.py#L947).
