### ISSUE TITLE
Implement torch.device 

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#327]
### 🚀 Feature

Implement [`torch.device`](https://pytorch.org/docs/stable/tensor_attributes.html#torch.device:~:text=float_tensor%20*%3D%20complex_float_tensor-,torch.device,-CLASS)

### Motivation

NeMo [Vision Transformer](https://github.com/NVIDIA/NeMo/blob/main/examples/vision/vision_transformer/megatron_vit_classification_pretrain.py)

cc @tfogal

**Comment by tfogal** [comment]
would like to discuss at triage review: can we just say `cuda` for everything? what about tensors from the outside (i.e. input tensors) that are on `cpu` or even things like `meta`?

**Comment by mruberry** [comment]
triage review — if the jit could annotate this function as constexpr and detect that the input is constexpr it could just call it
