### ISSUE TITLE
Implement TensorBase.is_cuda

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#329]
### 🚀 Feature

Implement [`TensorBase.is_cuda`](https://pytorch.org/docs/stable/generated/torch.Tensor.is_cuda.html)

### Motivation

NeMo [Vision Transformer](https://github.com/NVIDIA/NeMo/blob/main/examples/vision/vision_transformer/megatron_vit_classification_pretrain.py)

cc: @tfogal 

cc @tfogal

**Comment by k223kim** [comment]
Hey @athitten ! I'm a little confused. Don't we have this already? (https://github.com/Lightning-AI/lightning-thunder/issues/138)

Would you be able to explain how this is different from issue #138?

**Comment by athitten** [comment]
@k223kim I din't know support for `is_cuda` already existed. Probably the thunder I was using din't have it yet.

**Comment by tfogal** [comment]
Closing based on discussion above.
