### ISSUE TITLE
Implement TensorBase.is_complex

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#339]
### 🚀 Feature

Implement [`torch.is_complex`](https://pytorch.org/docs/stable/generated/torch.is_complex.html)

### Motivation

NeMo's [MegatronNeVaModel](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/multimodal_llm/neva/neva_pretrain.py)

cc @apaz-cli @tfogal

**Comment by khushi-411** [comment]
Hi, @athitten! I'd like to work on this issue. Thanks! :-)
