### ISSUE TITLE
Implement TensorBase.clone

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#342]
### 🚀 Feature

Implement [`TensorBase.clone`](https://pytorch.org/docs/stable/generated/torch.clone.html)

### Motivation

NeMo's [MegatronNeVaModel](https://github.com/NVIDIA/NeMo/blob/main/examples/multimodal/multimodal_llm/neva/neva_pretrain.py)

cc @tfogal

**Comment by mruberry** [comment]
triage review — let's implement this but not as a symbol and have it just return its input
