### ISSUE TITLE
Regression on thunder/benchmarks/targets.py

### ISSUE THREAD

**Issue by IvanYashchuk** [Lightning-AI/lightning-thunder#396]
## 🐛 Bug

Changes added in https://github.com/Lightning-AI/lightning-thunder/commit/b1f447022b0732e83c11661c30746568280834f7 (https://github.com/Lightning-AI/lightning-thunder/pull/279) introduced a regression on the benchmarks, for example,
```
pytest thunder/benchmarks/targets.py -vs -k 'test_nanogpt_gpt2_fwd[thunder]'
```
has a median time of about 4.3ms before the commit and 6.15ms with b1f447022b0732e83c11661c30746568280834f7.

Many other benchmark cases from benchmarks/targets.py are affected by the change.

`git revert b1f447022b0732e83c11661c30746568280834f7` on the current main restores the performance.

@t-vi, do you know what could be causing the slowdown?

cc @apaz-cli @crcrpar

**Comment by t-vi** [comment]
For my own reference, on my reference machine:
```
b1f447022b0732e83c11661c30746568280834f7^
test_nanogpt_gpt2_fwd[thunder]     13.0015  13.6725  13.1576  0.2891  13.0281  0.2124       1;1  76.0015       5           1

b1f447022b0732e83c11661c30746568280834f7
test_nanogpt_gpt2_fwd[thunder]     14.7374  15.5216  14.9018  0.3466  14.7441  0.2112       1;1  67.1059       5           1

4663b87e67955edec371c6f37a763a7ec358d835 (current main)
test_nanogpt_gpt2_fwd[thunder]     14.7783  15.2227  14.8889  0.1873  14.8131  0.1166       1;1  67.1642       5           1
```

**Comment by t-vi** [comment]
Has been reverted, so I'm reopening.
