### ISSUE TITLE
grad transform introduces reduction operation with NumberProxy in axes

### ISSUE THREAD

**Issue by jjsjann123** [Lightning-AI/lightning-thunder#403]
## 🐛 Bug

Found this issue in #286 , see comment https://github.com/Lightning-AI/lightning-thunder/pull/286#discussion_r1597889447

two issues that I want to raise regarding this:
1. NumberProxy shouldn't show up in trace. (look at the trace from torch executor.
```
@no_autocast
def backward_fn(saved_for_backward, cotangents):
  # saved_for_backward: "Collection"
  # cotangents: "Collection"
  C0, C1, = saved_for_backward
  clear_collection(saved_for_backward)
  del saved_for_backward
  t83, = cotangents
  clear_collection(cotangents)
  del cotangents
  t11, t15, t25, t26, t28, t38, t48, t52, t54, t58, t62, t64, t65, t66, t67, t70, \
  t71, t72, t74, t78, t79, t80, t_attn_c_attn_weight, t_attn_c_proj_weight, \
  t_mlp_c_fc_weight, t_mlp_c_proj_weight, = C0
  clear_collection(C0)
  del C0
  f40, f44, f67, f69, f71, i51, i6, = C1

  t411 = torch.sum(t409, i51, True, dtype=None)  # t411: "cuda:0 f32[2, 12, 1024, 1]"
    # t411 = ltorch.sum(t409, i51, True, dtype=None)  # t411: "cuda:0 f32[2, 12, 1024, 1]"
      # t552 = prims.sum(t409, (3,))  # t552: "cuda:0 f32[2, 12, 1024]"
      # t411 = prims.broadcast_in_dim(t552, [2, 12, 1024, 1], [0, 1, 2])  # t411: "cuda:0 f32[2, 12, 1024, 1]"
  del t409, i51
```
2. Nvfusion isn't handling reduction axes properly. Look at the trace from nvfuser executor, how i51 is not used in `prims.sum` and it instead baked it in as constant number.
```
  [t415] = nvFusion3(i51, t406, t48)
    # t30 = prims.iota(1024, start=0, step=1, device=devices.Device("cuda:0"), dtype=dtypes.int64)  # t30: "cuda:0 i64[1024]"
    # t31 = prims.broadcast_in_dim(t30, [1024, 1], [0])  # t31: "cuda:0 i64[1024, 1]"
    # t32 = prims.iota(1024, start=0, step=1, device=devices.Device("cuda:0"), dtype=dtypes.int64)  # t32: "cuda:0 i64[1024]"
    # t33 = prims.broadcast_in_dim(t32, [1, 1024], [1])  # t33: "cuda:0 i64[1, 1024]"
    # t34 = prims.add(t31, 0)  # t34: "cuda:0 i64[1024, 1]"
    # t35 = prims.broadcast_in_dim(t34, (1024, 1024), (0, 1))  # t35: "cuda:0 i64[1024, 1024]"
    # t36 = prims.broadcast_in_dim(t33, (1024, 1024), (0, 1))  # t36: "cuda:0 i64[1024, 1024]"
    # t37 = prims.ge(t35, t36)  # t37: "cuda:0 b8[1024, 1024]"
    # t38 = prims.broadcast_in_dim(t37, (2, 12, 1024, 1024), (2, 3))  # t38: "cuda:0 b8[2, 12, 1024, 1024]"
    # t409 = prims.mul(t48, t406)  # t409: "cuda:0 f32[2, 12, 1024, 1024]"
    # t410 = prims.sum(t409, (3,))  # t410: "cuda:0 f32[2, 12, 1024]"
    # t411 = prims.broadcast_in_dim(t410, [2, 12, 1024, 1], [0, 1, 2])  # t411: "cuda:0 f32[2, 12, 1024, 1]"
    # t412 = prims.broadcast_in_dim(t411, (2, 12, 1024, 1024), (0, 1, 2, 3))  # t412: "cuda:0 f32[2, 12, 1024, 1024]"
    # t413 = prims.sub(t406, t412)  # t413: "cuda:0 f32[2, 12, 1024, 1024]"
    # t414 = prims.mul(t48, t413)  # t414: "cuda:0 f32[2, 12, 1024, 1024]"
    # t415 = prims.where(t38, t414, 0.0)  # t415: "cuda:0 f32[2, 12, 1024, 1024]"
  del i51, t406, t48
```

### To Reproduce

`pytest thunder/tests/test_examine_memory.py -s -v -k test_nanogpt_block`

Might want to print out `bw_extrace` and verify the backtrace.

Reproduced on commit
```
commit d6237c88d26aa4a5541f3ad2e955140264afb068 (HEAD -> main, origin/main, origin/HEAD)
Author: Ivan Yashchuk <IvanYashchuk@users.noreply.github.com>
Date:   Fri May 10 18:26:46 2024 +0300

    Fix flaky test_prim_inplace_copy_fwd (#399)
```

**Comment by mruberry** [comment]
triage review —

- we think we can change the backward trace to use constant numbers instead of number proxies for now
- but we do want number proxies in the backward trace soon, so we should carefully consider their integration with nvfuser and grad, and imposing restraints like "this must be a constant value"
- maybe nvFuser's cache could detect the value of the NumberProxy?

**Comment by jjsjann123** [comment]
> so we should carefully consider their integration with nvfuser and grad, and imposing restraints like "this must be a constant value"

Imposing those constraints universally in thunder is what I'm planning to do.
When you mentioned explicitly about `integration`, I'm under the impression that you are trying to allow backend to propose constraints. I'm open to that discussion and have [an issue](https://github.com/Lightning-AI/lightning-thunder/issues/263) opened already. That might be a bit trickier to plumb through back to prologue trace.

Meanwhile, I think an easy way to unblock us for now is to just let integration reject things when seeing NumberProxy on those that `must be a constant value`. i.e. reduction axes for example.

**Comment by IvanYashchuk** [comment]
> NumberProxy shouldn't show up in trace.

Do you think NumberProxies shouldn't be used in traces, in general, today and in the future, or only today because of how it's not dynamic and only a wrapper around a constant today?

It's possible to modify the trace to unwrap all NumberProxies into actual values by modifying `backward_trace` after this line https://github.com/Lightning-AI/lightning-thunder/blob/4663b87e67955edec371c6f37a763a7ec358d835/thunder/core/transforms.py#L3961C5-L3961C49.

**Comment by jjsjann123** [comment]
> Do you think NumberProxies shouldn't be used in traces, in general, today and in the future, or only today because of how it's not dynamic and only a wrapper around a constant today?

I should be more careful with my wording :laughing:
Yes NumberProxies should be used in the trace in general. There're some rough corners (i.e. nvfuser's handling of baking in static number from proxies), but we should just patch those.

But I'm surprised to see NumberProxy show up with `thunder.jit` **today**. IIUC, that's what `TestExecutor.make_callable` uses for compilation. Current default caching logic is CONSTANT_VALUES, I thought that means everything gets baked in as static and I'm not sure where the NumberProxy is coming from.

Totally not pointing finger at grad transform. But I think in general NumberProxy should be treated differently with a plain Number. i.e. A NumberProxy means dynamic value and that should be respected by transforms.

**Comment by jjsjann123** [comment]
I'm closing this issue since I now understands where the number proxy is coming from in grad transform.

Looking forward to #231 fixing the issue.
