### ISSUE TITLE
Enable cuDNN executor by default

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#418]
## 🚀 Feature

Now that cudnn-fe is publicly installable, we should add it into the default executors.

### Motivation

cudnn often gives great performance :-)

### Pitch

https://github.com/Lightning-AI/lightning-thunder/blob/73ca5dc79179773c542d71b3f81d02ae0a220329/thunder/__init__.py#L162

this logic to be updated to include cudnn

### Additional context

we should be sure we are not regressing anything, and that may mean inserting new guards in the cudnn executor. Probably best to ask @parthmannan @mpatel31415 to try it

**Comment by parthmannan** [comment]
So far I have seen cuDNN SDPA give performance improvement and haven't seen any failures across a few models. Will test a few more models/configs and can confirm but I think enabling cuDNN executor by default would be beneficial.

**Comment by vedaanta** [comment]
Currently cudnn executor is overly optimistic when claiming sdpa. [Link](https://github.com/Lightning-AI/lightning-thunder/blob/main/thunder/executors/cudnnex.py#L370)
This change was made in #57. Before including cudnn executor in default list, the checker should be made stricter.

-------------

To address the pain point of debugging with cudnn executor, there is a custom `CudnnGraphNotSupportedException` starting v1.3. The sdpa checker function can throw errors with a pseudo code like:
```
def _cudnn_operation_checker(
    a: TensorLike
):
 
   try:
        _make_cudnn_operation_graph(a)
    except cudnn.cudnnGraphNotSupportedError as ex:
        return False
    except Exception as e:
        raise
```

Does the above approach look reasonable?
Any unhandled exceptions throw will be either bugs to solve or user errors.

**Comment by tfogal** [comment]
> cudnn executor is overly optimistic when claiming sdpa.

ahh; yes, we should fix that first. Thanks for remembering this!

> sdpa checker function can throw errors with a pseudo code like:

Yeah, this seems like a great approach to me!
