### ISSUE TITLE
Likely memory fragmentation for larger models

### ISSUE THREAD

**Issue by parthmannan** [Lightning-AI/lightning-thunder#420]
## 🐛 Bug

Running LLaMa2 13B with FSDP ZeRO2 on 8xH100

```
torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --model_name Llama-2-13b-hf --compile thunder_cudnn --distributed_mode fsdp --shard_mode zero2 --bucketing_mode none --micro_batch_size 1 --global_batch_size 8
```
`Average iter time: 867.59 ms`
The performance looks worse than expected and on inspecting the timeline, there is a large portion where GPU is idle as there are many `cudaMalloc` and `cudaFree` memory operations happening.

<img width="1240" alt="Screenshot 2024-05-15 at 12 56 45 PM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/b5a54378-06f1-4154-959f-317ee0286cd2">

Using expandable_segments in PyTorch, the performance significantly improves and there is no gap in the timeline.
```
PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=8 --nnodes=1 benchmark_litgpt.py --model_name=Llama-2-13b-hf --compile thunder_cudnn --distributed_mode=fsdp --shard_mode zero2 --bucketing_mode none --micro_batch_size 1 --global_batch_size 8
```
`Average iter time: 729.44 ms`

<img width="1240" alt="Screenshot 2024-05-15 at 12 56 49 PM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/cfb0c942-5400-4dc0-990f-f02607c1b89c">

We should find out if this memory fragmentation is due to Thunder's interaction with the PyTorch memory allocator or something else.

**Comment by parthmannan** [comment]
@kshitij12345 - From our discussion, I remember you were looking into this. I believe this is what is causing the memory operations but needs further investigation.

**Comment by tfogal** [comment]
cc @eqy re: fragmentation lunch discussion

**Comment by eqy** [comment]
Does `TORCH_NCCL_AVOID_RECORD_STREAMS=1` help?

**Comment by kshitij12345** [comment]
As per offline discussion with @ptrblck , we should enable `TORCH_NCCL_AVOID_RECORD_STREAMS=1` by default in `thunder`.

**Comment by parthmannan** [comment]
cc - @IvanYashchuk @mruberry Can we enable this env var by default in Thunder or should we rely on nvidia containers do enable this?

**Comment by csarofeen** [comment]
Ping @IvanYashchuk @ptrblck @eqy 
Any reason why we shouldn't enable this by default?

**Comment by IvanYashchuk** [comment]
Let's set this variable on by default for Thunder-generated functions.

Quoting Carilli from the PR description that added this env variable:
> Because we're juggling razor blades here and it's hard to test, recordStream avoidance is off by default, and existing default (aka recordStream-based) behavior is unchanged. 

Since it's hard to test, let's enable it in Thunder by default.

Linking here relevant forum post for curious people: https://discuss.pytorch.org/t/cuda-allocation-lifetime-for-inputs-to-distributed-all-reduce/
