### ISSUE TITLE
Cuda only? 

### ISSUE THREAD

**Issue by AmgadHasan** [Lightning-AI/lightning-thunder#43]
Hi

Thanks for sharing this with the community. Much appreciated.

I am wondering if this works only with cuda hardware. For example, does it work with AMD GPUs through rocm?

**Comment by lantiga** [comment]
Hey, we haven’t done work to target ROCm, our focus now is squarely on CUDA.

Having said that, it would essentially require you to add ROCm friendly executors (the PyTorch eager and torch.compile executors are already).
