### ISSUE TITLE
benchmark_litgpt.py + Llama-3-8B + FSDP hits OOM since 5/4/24 on H100

### ISSUE THREAD

**Issue by xwang233** [Lightning-AI/lightning-thunder#439]
## 🐛 Bug

benchmark_litgpt.py + Llama-3-8B + FSDP hits OOM since 5/4/24 on H100

### To Reproduce

```
torchrun --nproc-per-node=8 /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py --micro_batch_size 1 --model_name Llama-3-8B --distributed_mode fsdp --shard_mode zero2 --compile thunder_cudnn
```

on H100 80 GB

#### Code sample

see above

### Expected behavior

no oom

### Environment

OOM pjnl-20240504:
- nvfuser: nvidia/fuser@4e8356915fc6ffa823cf97fed4249cc00f317fdf
- thunder: cab020881765594fd9552d4deb8cc4e0f64410d2
- torch: pytorch/pytorch@dd92637f445d2787f83829079276f71b1ad1fc7c
- litgpt==0.3.0
- cuda 12.4.1.003
- cudnn 9.1.0.70

works pjnl-20240503:
- nvfuser: nvidia/fuser@d12b786dd7782c0ea5d087c36fd0497ad92ff7dd
- thunder: 90a0f4c0d0a90d1e94684a847f3adfe2230985b4
- torch: pytorch/pytorch@aa7be72cc55244978ddaf760338dab6b9cf977a1
- litgpt==0.3.0
- cuda 12.4.1.003
- cudnn 9.1.0.70

### Additional context

N/A

cc @tfogal @mpatel31415 @crcrpar

**Comment by xwang233** [comment]
Thanks @tfogal  for the insights. Reverting 85b2cd86d868fc7d85bab816b4160a10205c67d7 fixes the OOM. 

https://github.com/Lightning-AI/lightning-thunder/pull/45

cc @crcrpar

**Comment by crcrpar** [comment]
why do you think the pr is the cause?
