### ISSUE TITLE
Unexpected keyword arg 'inplace' for torch.nn.SiLU 

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#455]
### 🐛 Bug

NeMo's StableDiffusion uses [SiLU](https://pytorch.org/docs/stable/generated/torch.nn.SiLU.html) activation in its UNet model. When `UNet` stage is run with `thunder.jit`, thunder gives an error:
`silu() got an unexpected keyword argument 'inplace'`.
Specifically the error is is raised in this [line](https://github.com/pytorch/pytorch/blob/v2.3.0/torch/nn/modules/activation.py#L396) of `torch/nn/modules/activation.py` although `inplace` is a valid argument of the op.

CC: @tfogal 

cc @tfogal

**Comment by tfogal** [comment]
I had a chat with @athitten on this one. THe SiLu in question is purely internal to the model--we could just functionalize this as a solution.

**Comment by mruberry** [comment]
triage review —

- we can add the inplace argument to the signature and throw a NotImplementedError if it's True for now, that will also provide a more informative error message to tell us if this is actually being used inplace
- we should revisit general inplace operator support with Q3 planning
