### ISSUE TITLE
TypeError with torch.finfo()

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#457]
### 🐛 Bug

NeMo's Stable Diffusion uses HuggingFace Transformers that uses `torch.finfo` in one of its operations. When `thunder.jit` is used with Stable Diffusion, it gives an error:
```
TypeError (note: full exception trace is shown but execution is paused at: _run_module_as_main)
finfo(): argument 'type' (position 1) must be torch.dtype, not floating
```
although torch supports the `dtype` in `torch.finfo(dtype)` to be either `torch.float32` or just `float32`.

CC: @tfogal 

cc @tfogal

**Comment by tfogal** [comment]
Not really understanding this one. We don't appear to have a lookaside for `torch.finfo`; should we?

**Comment by t-vi** [comment]
```
torch.finfo(thunder.dtypes.float32)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[14], line 1
----> 1 torch.finfo(thunder.dtypes.float32)

TypeError: finfo(): argument 'type' (position 1) must be torch.dtype, not floating
```

likely options:
- fix gap in translating thunder dtypes to torch.dtype transparently,
- add torch.finfo lookaside

As an aside: Quite likely, it would help debugging these cases if Thunder objects had more Pythonic representations that informed about the fact that they are thunder objects...  (ported over #510 for this)

**Comment by athitten** [comment]
@athitten to add the full trace.

**Comment by tfogal** [comment]
dropping 'triage review' until the trace comes in, will revisit then.

**Comment by t-vi** [comment]
Repro:

```
import torch, thunder

def fn(x):
    return torch.finfo(x.dtype).min

a = torch.randn(5, 5)

jfn = thunder.jit(fn)

jfn(a)
```

Aside from the obvious implementation strategy of implementing finfo: Maybe it would be nice to do a replacement of thunder dtype (and device) to PyTorch when calling opaque functions.

**Comment by k223kim** [comment]
Hello Team! FYI I will be working on this issue. (cc. @t-vi )

**Comment by t-vi** [comment]
Thank you @k223kim
