### ISSUE TITLE
TypeError with torch.nn.functional.pad

### ISSUE THREAD

**Issue by athitten** [Lightning-AI/lightning-thunder#458]
### 🐛 Bug

NeMo's Stable Diffusion uses `torch.nn.functional.pad` as below:

`x = torch.nn.functional.pad(x, pad, mode="constant", value=0)`

When run with `thunder.jit`, it gives a `TypeError`:
`Expected the numbertype <class 'float'>, corresponding to the dtype float32, but found the numbertype <class 'int'>!`
although `torch.nn.functional.pad` supports `value=0` along with float `value=0.0`

CC: @tfogal

**Comment by tfogal** [comment]
Thanks, @athitten !
If you have a minute sometime, it would be helpful for you to verify that #459 actually fixes the context that you hit this in NeMo.
