### ISSUE TITLE
Thunder is 10**6 times slower than Lightning 

### ISSUE THREAD

**Issue by kurmukovai** [Lightning-AI/lightning-thunder#46]
## 🐛 Bug
I feel like marketing is misleading, as thunder is 1_000_000 times slower than lightning^[1,2]

![image](https://github.com/Lightning-AI/lightning-thunder/assets/14237010/44b07c43-4f3b-40ab-8fb4-14a7ab48c982)

1. https://en.wikipedia.org/wiki/Speed_of_light
2. https://en.wikipedia.org/wiki/Speed_of_sound

**Comment by lantiga** [comment]
😁 Right but AI helps us defy the laws of physics (Karpathy) 😅

**Comment by Andrei-Aksionov** [comment]
```text
Thunder, feel the thunder
Lightning, then the thunder
```
(Imaging Dragons - Thunder)
