### ISSUE TITLE
Nous-Hermes-13b on 1x8 H100 FSDP zero2 with thunder_cudnn is 23% slower than with inductor

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#477]
## 🐛 Bug

Nous-Hermes-13b  with FSDP zero2 trained on 1 node with 8 H100 each is considerably slower for `thunder_cudnn` than `inductor`. 
 
### To Reproduce

It was tested on Slurm cluster. You can contact me on Slack for more details
1. Create a file `script.sh` (second version will be with  `--compile  inductor'):

```
#!/bin/bash
#SBATCH -A YOUR_DETAILS
#SBATCH -p batch
#SBATCH -J YOUR_DETAILS
#SBATCH -N 2
#SBATCH --ntasks-per-node 8
#SBATCH --time 0:29:00
#SBATCH --mail-type=FAIL
#SBATCH --exclusive


IMAGE="INTERNAL_IMAGE:pjnl-20240524"

TRAINING_CMD="python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
 --model_name Nous-Hermes-13b  \
 --micro_batch_size 2 \
 --distributed_mode fsdp \
 --shard_mode zero2 \
 --compile thunder_cudnn 
"
```
2.  After you are logged into Slurm cluster run:
```
sbatch script.sh
 ```
3. The results should be visible in `slurm-JOB_ID.out` file. 

### Expected behavior

The time of training iteration should be similar in both cases. 

### Environment

As in the docker image used.

**Comment by mruberry** [comment]
triage review — @parthmannan - what's going on here?

**Comment by parthmannan** [comment]
Thanks @mruberry We'll take a look.

@mpatel31415 - Did we try `thunder_inductor_cat_cudnn` on this? The architecture is very similar to LLaMa and without `inductor_cat`, the RoPE performance is expected to perform worse.

**Comment by parthmannan** [comment]
This is actually quite interesting. Despite no RoPE support, thunder_cudnn outperforms inductor on mbs=1
### Time per iter
```
eager: 528.17 ms
inductor: 496.06 ms
thunder_cudnn: 452.87 ms
```
`thunder_inductor_cat_cudnn` fails to run. Will need to investigate and file an issue for that separately.

But on MBS=2, the performance degrades quite a bit leading to the slowdown. More in next comment.

**Comment by parthmannan** [comment]
### MBS=2 Time per iter
```
eager: 878.01 ms
inductor: 762.20 ms
thunder_cudnn: 996.90 ms
```

Now, here's what the profile looks like - 

There are two very large ReduceScatter kernels that are not seen in `inductor`.
<img width="1553" alt="Screenshot 2024-06-04 at 1 00 55 AM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/7ff9a16f-484d-4586-9f61-6014452e169a">

<img width="1553" alt="Screenshot 2024-06-04 at 1 01 02 AM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/e7b5d977-df9e-4689-b183-49690b138fa5">

So either other GPUs are not participating at the same time and there is large jitter in the execution OR FSDP over 2 nodes is causing the delay.

Taking a look at what is going with other GPUs tells us that there is some kind of memory operations that are causing the ReduceScatter to wait for data causing large delays making jitter the likely cause.

This corresponds to the first large RS and is actually present on multiple GPUs.
<img width="1553" alt="Screenshot 2024-06-04 at 1 01 15 AM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/7429d692-42ec-4093-ae6f-e43845855783">

This corresponds to the first large RS and is actually present on multiple GPUs.
<img width="1553" alt="Screenshot 2024-06-04 at 1 01 44 AM" src="https://github.com/Lightning-AI/lightning-thunder/assets/38387286/03f1b98f-6f7f-4fd5-8b75-a2352b020b80">

We need to find out why these memory operations exist in the timeline on some GPUs when using Thunder. Is there any reason for memory thrashing or other memory issues to pop on some GPUs and not on others?

**Comment by parthmannan** [comment]
Oh well, all the time spent debugging the above issue led me back to #420 
Setting `TORCH_NCCL_AVOID_RECORD_STREAMS=1` solves the issue and this is being added by default to Thunder in #512 
Performance is now `thunder_cudnn: 730.59 ms` which is faster than `inductor`.

Marking this closed for now as the fix for underlying issue is underway. Please feel free to reopen if needed.
