### ISSUE TITLE
Training Llama-2-13b-hf on 2x8 H100 with Thunder inductor is 47% slower than with Inductor 

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#485]
## 🐛 Bug

Llama-2-13b-hf  with FSDP zero2 trained on 2 nodes with 8 H100 each is much slower for `thunder_inductor_cat_cudnn` than `inductor`. 
 
### To Reproduce

It was tested on Slurm cluster. You can contact me on Slack for more details
1. Create a file `script.sh` (second version will be with  `--compile  inductor'):

```
#!/bin/bash
#SBATCH -A YOUR_DETAILS
#SBATCH -p batch
#SBATCH -J YOUR_DETAILS
#SBATCH -N 2
#SBATCH --ntasks-per-node 8
#SBATCH --time 0:29:00
#SBATCH --mail-type=FAIL
#SBATCH --exclusive


IMAGE="INTERNAL_IMAGE:pjnl-20240524"

TRAINING_CMD="python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py \
 --model_name Llama-2-13b-hf  \
 --micro_batch_size 1 \
 --distributed_mode fsdp \
 --shard_mode zero2 \
 --compile thunder_inductor_cat_cudnn 
"
```
2.  After you are logged into Slurm cluster run:
```
sbatch script.sh
 ```
3. The results should be visible in `slurm-JOB_ID.out` file.

For thunder_inductor_cat_cudnn:
iter 44: loss 4.6562, iter time: 1288.18ms, t: 4096

For inductor:
iter 44: loss 4.6562, iter time: 794.42ms, t: 4096

(actually 47% was calculated on averages from a few iterations)
### Expected behavior

We should see comparable speed for  `thunder_inductor_cat_cudnn` than `inductor`. 

### Environment

As in the docker image used.

**Comment by parthmannan** [comment]
@mpatel31415 Can you try rerunning with `TORCH_NCCL_AVOID_RECORD_STREAMS=1`? I believe this is the same as #420 and #477 and is being fixed by #512 by default but meanwhile if you could try that, that'd be great.

**Comment by mpatel31415** [comment]
@parthmannan Yes this solves the issue! Now we get 732.73ms. 
Do you know when #512 might be merged and propagated to image pjnl-latest?  I'm wondering if we should fix it on our side for the next run or it won't be needed.

**Comment by IvanYashchuk** [comment]
We will close the issue once https://github.com/Lightning-AI/lightning-thunder/pull/512 is merged.

**Comment by t-vi** [comment]
#512 is merged.
