### ISSUE TITLE
Thunder object's `__repr__` should indicate what object they are (TensorProxy and others)

### ISSUE THREAD

**Issue by t-vi** [Lightning-AI/lightning-thunder#510]
An older issue in the old repo was for TensorProxy, but it also affects other types. Here is the old discussion:

Currently `TensorProxy __repr__` returns just the name.
This is bad because it is obscuring error messages which include `TensorProxy` mentions.

Note that we should use `<TensorProxy {self.name}>` or so. Using `[...]` should only be for lists (please!), as it will look like lists.
Python itself uses `<{type} object ...>` as repr, I'm not attached to "object", but it generally seems a good idea to follow the example with `<...>`.

@mruberry commented: We probably are implicitly relying on `TensorProxy.__repr__` printing just the name, but we should be able to fix our reliance on that without too much code change

Similar considerations apply to other objects (e.g. dtypes).

cc @apaz-cli

**Comment by k223kim** [comment]
Hi Team! Just as a FYI, I am interested in handling this issue :)
