### ISSUE TITLE
Add `post_optimization_transform` to `thunder.jit`

### ISSUE THREAD

**Issue by kshitij12345** [Lightning-AI/lightning-thunder#533]
Support to add transforms which will be applied after the `transform_for_execution/optimization` pass is done. This will help enable transforms to help with profiling (like adding nvtx markers on the execution trace), adding debug prints or checks, etc

One question, what should be the signature of this transform?
Option 1: `def transform(trace)` - Takes single trace at a time and it is passed `forward` and `backward` computation trace one by one.
Option 2: `def transform(fwd_trace, bwd_trace)` - Takes both `forward` and `backward` traces (`backward` trace could be None) and applies the transform to both. This would allow the transform to consider both traces if it wants to or apply independently.

cc: @IvanYashchuk @t-vi

**Comment by crcrpar** [comment]
I'd suggest defining interfaces for both cases so that thunder can tell which case a user wants. An example would look as follows 

```
class AdditionalTransform(ABC):
    @abstractmethod
    def __call__(self, trace: TraceCtx) -> TraceCtx:
        ...

class FwdBwdAdditionalTransform(ABC):
    @abstractmethod
    def __call__(self, fwd_trace: TraceCtx, bwd_trace: TraceCtx) -> tuple[TraceCtx, TraceCtx]:
        ...
```

We could define another for the existing `add_transform` as well

**Comment by IvanYashchuk** [comment]
> One question, what should be the signature of this transform?

My preference is option 1 because I'm not convinced that backward trace would continue to exist in the current form. I plan to change it and having `transform(trace)` would help me isolate the changes.
