### ISSUE TITLE
thunder/tests/test_nvfuser_remat.py::test_find_cut_dropout_nvfuser_cuda_None is over sensitive. 

### ISSUE THREAD

**Issue by wujingyue** [Lightning-AI/lightning-thunder#549]
I believe it's a problem with the test, but please correct me if I'm wrong. 

To reproduce, check out https://github.com/Lightning-AI/lightning-thunder/tree/wjy/bookend and run `$ pytest thunder/tests/test_nvfuser_remat.py -k test_find_cut_dropout_nvfuser_cuda_None`. 

```
FAILED thunder/tests/test_nvfuser_remat.py::test_find_cut_dropout_nvfuser_cuda_None - AssertionError: assert 't5' == 't11'
```

The Thunder trace:
```
# Constructed by Delete Last Used (took 0 milliseconds)
import torch
from thunder.executors.torchex import no_autocast

@torch.no_grad()
@no_autocast
def _value_and_grad(*args):
  # args: "Collection"
  [t1] = nvFusion0()
    # t1 = prims.full((2, 2), 1, device=devices.Device("cuda:0"), dtype=dtypes.float32)  # t1: "cuda:0 f32[2, 2]"
  t0, = args
  del args
  [t11, t5, t9] = nvFusion1(t0)
    # t2 = prims.exp(t0)  # t2: "cuda:0 f32[2, 2]"
    # t3 = prims.exp(t2)  # t3: "cuda:0 f32[2, 2]"
    # t4 = prims.uniform((2, 2), 0.0, 1.0, device=devices.Device("cuda:0"), dtype=dtypes.float32)  # t4: "cuda:0 f32[2, 2]"
    # t5 = prims.lt(t4, 0.9)  # t5: "cuda:0 b8[2, 2]"
    # t6 = prims.convert_element_type(t5, dtypes.float32)  # t6: "cuda:0 f32[2, 2]"
    # t7 = prims.mul(t3, t6)  # t7: "cuda:0 f32[2, 2]"
    # t8 = prims.mul(t7, 1.1111111111111112)  # t8: "cuda:0 f32[2, 2]"
    # t9 = prims.exp(t8)  # t9: "cuda:0 f32[2, 2]"
    # t11 = prims.transpose(t9, (1, 0))  # t11: "cuda:0 f32[2, 2]"
  t10 = torch.matmul(t9, t9)  # t10: "cuda:0 f32[2, 2]"
    # t10 = ltorch.matmul(t9, t9)  # t10: "cuda:0 f32[2, 2]"
      # t10 = prims.matmul(t9, t9)  # t10: "cuda:0 f32[2, 2]"
  t12 = torch.matmul(t1, t11)  # t12: "cuda:0 f32[2, 2]"
    # t12 = ltorch.matmul(t1, t11)  # t12: "cuda:0 f32[2, 2]"
      # t12 = prims.matmul(t1, t11)  # t12: "cuda:0 f32[2, 2]"
  t14 = torch.matmul(t11, t1)  # t14: "cuda:0 f32[2, 2]"
    # t14 = ltorch.matmul(t13, t1)  # t14: "cuda:0 f32[2, 2]"
      # t14 = prims.matmul(t13, t1)  # t14: "cuda:0 f32[2, 2]"
  del t11, t1
  [t23] = nvFusion2(t0, t12, t14, t5, t9)
    # t2 = prims.exp(t0)  # t2: "cuda:0 f32[2, 2]"
    # t3 = prims.exp(t2)  # t3: "cuda:0 f32[2, 2]"
    # t6 = prims.convert_element_type(t5, dtypes.float32)  # t6: "cuda:0 f32[2, 2]"
    # t15 = prims.add(t12, t14)  # t15: "cuda:0 f32[2, 2]"
    # t16 = prims.mul(t15, t9)  # t16: "cuda:0 f32[2, 2]"
    # t18 = prims.mul(1.1111111111111112, t16)  # t18: "cuda:0 f32[2, 2]"
    # t19 = prims.mul(t6, t18)  # t19: "cuda:0 f32[2, 2]"
    # t22 = prims.mul(t19, t3)  # t22: "cuda:0 f32[2, 2]"
    # t23 = prims.mul(t22, t2)  # t23: "cuda:0 f32[2, 2]"
  del t0, t12, t14, t5, t9
  return (t10, (t23,))
```

[The cut](https://github.com/Lightning-AI/lightning-thunder/blob/126940750c8e498a89376e6c787985448c79808a/thunder/tests/test_nvfuser_remat.py#L311) is `t0, t5, t9`, the same as with bookend. However, due to bookend being disabled, `t11` becomes an output of nvFusion1, breaking the checks here: https://github.com/Lightning-AI/lightning-thunder/blob/126940750c8e498a89376e6c787985448c79808a/thunder/tests/test_nvfuser_remat.py#L313-L317

**Comment by IvanYashchuk** [comment]
Do you have a preference on how to update this test? It can be updated to be tested against new correct output together with the change that turns off the bookend optimization.

**Comment by wujingyue** [comment]
I might have tagged the wrong person. Apparently, @jjsjann123 [changed the test](https://github.com/Lightning-AI/lightning-thunder/commit/6deb2cc2a5707b7f2d4a6af25c5cb2505e9be084#diff-a1ec55674261afa8d49060fd07e812af60d3418c06ea28d5f38d2b4c02b3cdd2) most recently. The test *before that change* would pass. 

> Do you have a preference on how to update this test? It can be updated to be tested against new correct output together with the change that turns off the bookend optimization.

I don't understand rematerialization and this test enough to make a recommendation. In general, the test as is assumes tensors of certain semantics appear in a certain order, which is a bit too fragile. We could check for the new order (the one without bookend) as you said, but it would still feel to me like https://testing.googleblog.com/2013/08/testing-on-toilet-test-behavior-not.html.

**Comment by jjsjann123** [comment]
Yes, the test isn't very stable.

i.e. my code change was addressing the issue in CI where the trace somehow got different variable names for the same TensorProxy... 

> The test before that change would pass.

Is that verified in CI? i.e. when I made the changes back then, I cannot verify the CI failure neither and that's frustrating by itself.

Anyway, I think a better approach might be to identify the tensor names on the vanilla trace `traces[0]` before fusion and use that as a check? Though I'm not sure if the PR modifying the fusion logic would indeed change the rematerialization result, but looks like it didn't in this example.

**Comment by jjsjann123** [comment]
@wujingyue I think for the sake of your bookend PR, it's probably ok to unblock you by updating the check to be
```
    assert cut[0] == producer.args[0].name
    # Note cut[1]/producer.output[0] is the boolean mask for dropout. It should
    # be chosen over the float32 mask. See this issue: "The Recomputation
    # Algorithm on Dropout choses a float32 mask to save"
    assert cut[1] == producer.output[1].name
    assert cut[2] == producer.output[2].name
```

**Comment by wujingyue** [comment]
> Is that verified in CI?

I printed out `cut` by hand and it's `t0, t5, t9`. 

> it's probably ok to unblock you by updating the check to be

SG!

**Comment by jjsjann123** [comment]
> > Is that verified in CI?
> 
> I printed out `cut` by hand and it's `t0, t5, t9`.

Yeah that's what I see on my local machine in [the PR you linked](https://github.com/Lightning-AI/lightning-thunder/commit/6deb2cc2a5707b7f2d4a6af25c5cb2505e9be084#diff-a1ec55674261afa8d49060fd07e812af60d3418c06ea28d5f38d2b4c02b3cdd2) as well. But CI is getting a different name for those tensors and I couldn't repro neither, see this comment: https://github.com/Lightning-AI/lightning-thunder/pull/286#issuecomment-2111244249

:shrug:

**Comment by wujingyue** [comment]
Oh, I see what you mean now. Good point!
