### ISSUE TITLE
TransformerEngine: Communication and Computation is not overlapped in backward pass with FSDP Zero3

### ISSUE THREAD

**Issue by kshitij12345** [Lightning-AI/lightning-thunder#557]
Repro -
Generate the profile with 
`nsys profile -c cudaProfilerApi torchrun --nproc_per_node=8 --nnodes=1 thunder/benchmarks/benchmark_litgpt.py --return_metrics_as_json=True --json_path=/tmp/benchmark_litgpt_data.json --distributed_mode=fsdp --shard_mode=zero3 --model_name=Llama-2-7b-hf --micro_batch_size=1 --compile=thunder_inductor_cat_transformerengine_cudnn --nsys_enabled=True --dynamic=False`

In the image below, it can be seen that once backward pass begins, there is almost no overlap between comms and compute (there should be some overlap in reduce scatters and computations).
![te_backward_compute](https://github.com/Lightning-AI/lightning-thunder/assets/19503980/3e52ee4f-0eec-48d7-b235-2654fe9aafb9)

Zoomed out timeline:
![te_backward_compute_2](https://github.com/Lightning-AI/lightning-thunder/assets/19503980/ead42bcb-2b1d-48a8-8aee-c03d2b29145b)

If `TE` executors is removed then most of the computation and communication is overlapping (see below)
![image](https://github.com/Lightning-AI/lightning-thunder/assets/19503980/beef5bb6-4262-480c-96d5-8d991196d766)

-----------
~~My first guess is that the blocking `all_reduce` called on `fp8_autocast_exit` could be the reason.~~ -> This is incorrect.

Blocking AllReduce: https://github.com/NVIDIA/TransformerEngine/blob/0edf30b87159e82048b5f248e4b379aebb8f364a/transformer_engine/pytorch/fp8.py#L302-L313
fp8_autocast_exit: https://github.com/NVIDIA/TransformerEngine/blob/0edf30b87159e82048b5f248e4b379aebb8f364a/transformer_engine/pytorch/fp8.py#L420-L421

**Comment by kshitij12345** [comment]
Finding - Turns out that the passes `sort_communication_ops` and `limit_in_flight_allgathers` move the reduce_scatters to the end when TE is present.

**Comment by kshitij12345** [comment]
Applying the patch - to disable comms sorting on bw_trace, we can see overlap in comms and compute stream as well as slightly improved timings. Will investigate why all comms are moved to the last when `TE` executors is present.

cc: @kiya00 - if you have any idea as to why this happens.

```patch
diff --git a/thunder/executors/torch_autograd.py b/thunder/executors/torch_autograd.py
index 820359f..2130d5c 100644
--- a/thunder/executors/torch_autograd.py
+++ b/thunder/executors/torch_autograd.py
@@ -229,12 +229,12 @@ def split_forward_backward(computation_trc: TraceCtx, compile_data, compile_stat
                 3,
                 compile_data.fn.bucketing_strategy != FSDPBucketingStrategy.NONE,
             )
-            bw_extrace = sort_communication_ops(bw_extrace)
-            bw_extrace = limit_in_flight_allgathers(
-                bw_extrace,
-                3,
-                compile_data.fn.bucketing_strategy != FSDPBucketingStrategy.NONE,
-            )
+            # bw_extrace = sort_communication_ops(bw_extrace)
+            # bw_extrace = limit_in_flight_allgathers(
+            #     bw_extrace,
+            #     3,
+            #     compile_data.fn.bucketing_strategy != FSDPBucketingStrategy.NONE,
+            # )
         if getattr(compile_data.fn, "sharding_strategy") == FSDPType.ZERO2:
             from thunder.distributed import FSDPBucketingStrategy
             from thunder.distributed.utils import limit_in_flight_allgathers
```

Before Patch
```
iter 40: loss 4.6250, iter time: 305.65ms, t: 4096
iter 41: loss 4.6562, iter time: 305.29ms, t: 4096
iter 42: loss 4.6562, iter time: 305.02ms, t: 4096
iter 43: loss 4.6250, iter time: 308.57ms, t: 4096
iter 44: loss 4.6562, iter time: 305.58ms, t: 4096
Model name: Llama-2-7b-hf
Seq Length: 4096
Micro BS: 1
Global BS: 8
Number of Layers: 32
Number of parameters: 0.84B
Distributed Mode: fsdp
Sharding Mode: zero3
Bucketing: none
Compiler: thunder_inductor_cat_transformerengine_cudnn
Average iter time: 306.92 ms
Memory used: 52.91 GB
Tokens/s: 106764.90
Tokens/s/GPU: 13345.61
TFLOP/s: 4920.25
```

After Patch
```
iter 40: loss 4.6562, iter time: 297.87ms, t: 4096
iter 41: loss 4.6562, iter time: 295.52ms, t: 4096
iter 42: loss 4.6562, iter time: 297.42ms, t: 4096
iter 43: loss 4.6562, iter time: 294.58ms, t: 4096
iter 44: loss 4.6562, iter time: 294.62ms, t: 4096
Model name: Llama-2-7b-hf
Seq Length: 4096
Micro BS: 1
Global BS: 8
Number of Layers: 32
Number of parameters: 0.84B
Distributed Mode: fsdp
Sharding Mode: zero3
Bucketing: none
Compiler: thunder_inductor_cat_transformerengine_cudnn
Average iter time: 296.04 ms
Memory used: 52.92 GB
Tokens/s: 110728.12
Tokens/s/GPU: 13841.02
TFLOP/s: 5102.90
```

Profile (after patch)
![image](https://github.com/Lightning-AI/lightning-thunder/assets/19503980/8c7d4add-729d-407f-b6fa-19ab1666fedc)

**Comment by kiya00** [comment]
oh, let me think about it, at a rough glance, I think the reason is the `sort_communication_ops` which sorts the ops bottom-up based on the topology and weights we specify, and this sorting is not enough to realize the expectation, let reduce_scatter as far away as from wait. We probably need a reordering starting from the producer of reduce scatter, instead of the current sorting using topology+weights 
cc: @IvanYashchuk

**Comment by kiya00** [comment]
Hi @kshitij12345 , since the `sort_communication_ops` function is also used in zero2, I opened another issue #574 to record the problem, I think it's the similar reason as in #277, sorry for taking your time to do the nsys analysis 😢 

And I find that the `te_sync_fp8_meta_bwd` seems to appear after the `return` in the bwd trace, that's a problem, right?
`torchrun --nproc_per_node=2 --nnodes=1 thunder/benchmarks/benchmark_litgpt.py --return_metrics_as_json=True --json_path=/tmp/benchmark_litgpt_data.json --distributed_mode=fsdp --shard_mode=zero3 --model_name=Llama-2-7b-hf --micro_batch_size=1 --compile=thunder_inductor_cat_transformerengine_cudnn`
```
# in backward trace with n_layers=2, 
  [t1363] = nvFusion9(t1359)
    # t1361 = prims.convert_element_type(t1359, dtypes.float32)  # t1361: "cuda:0 f32[32000, 4096]"
    # t1362 = prims.div(t1361, 2.0)  # t1362: "cuda:0 f32[32000, 4096]"
    # t1363 = prims.convert_element_type(t1362, dtypes.bfloat16)  # t1363: "cuda:0 bf16[32000, 4096]"
  del t1359
  p1364 = torch_reduce_scatter_prim_impl(t1363, _DistributedReduceOps_0, _torch_distributed_distributed_c10d_ProcessGroup_1, True, None)  # p1364: "FUTURE cuda:0 bf16[16000, 4096]"
  del t1363
  t1365 = torch_wait_prim_impl(p1364)  # t1365: "cuda:0 bf16[16000, 4096]"
  del p1364
  return (None, None, t1445, None, t1440, t1435, t1430, t1425, t1420, t1415, t1410, t1405, t1400, t1395, t1390, t1385, t1380, t1375, t1370, t1365)
  te_sync_fp8_meta_bwd()
```

**Comment by kshitij12345** [comment]
@kiya00 No worry, thank you very much for looking into this!

> And I find that the te_sync_fp8_meta_bwd seems to appear after the return in the bwd trace, that's a problem, right?

This is certainly bad, will have a look. Thank you!
