### ISSUE TITLE
Make cudnnex SDPA checkers more conservative. 

### ISSUE THREAD

**Issue by wujingyue** [Lightning-AI/lightning-thunder#58]
#57's description and https://github.com/Lightning-AI/lit-thunder-LEGACY/pull/2480#issuecomment-2013537240 have the context. 

The proposed improvement is to properly propagate graph-not-supported errors from the cudnn backend to the frontend as distinguishable exceptions. This way, we can make the checkers to only reject unsupported graphs and not hiding other programming errors.

**Comment by vedaanta** [comment]
https://github.com/Lightning-AI/lightning-thunder/pull/427

Closing as the issue had already been addressed in above PR.
