### ISSUE TITLE
Transforms as EarlyTransforms

### ISSUE THREAD

**Issue by t-vi** [Lightning-AI/lightning-thunder#640]
Currently we have [grad](https://github.com/Lightning-AI/lightning-thunder/blob/fa55b090d88d769b926f67ea71087c5660f730bc/thunder/core/transforms.py#L1430) and [noop](https://github.com/Lightning-AI/lightning-thunder/blob/fa55b090d88d769b926f67ea71087c5660f730bc/thunder/core/transforms.py#L510) as AdditionalTransforms, however we might want to move them to early transforms to be able to work with epilogue-carrying functions.

Also, we have vjp, vmap and others that currently do now work well with jitted models and for which we should also do something (i.e. figure out what it means to change the input signature), what do we want to do when a module is involved? One option could be to just work on the arguments and ignore the model in the background. (If we want to support that at all.)

My idea would be to adapt these to work on the traces directly rather than the current indirection.

I'm filing this issue to discuss this, and then we see how to move things forward.

**Comment by mruberry** [comment]
triage review: the design tag marks issues where we want people to review and propose a design (possibly with a linked PR to see a sample implementation), so look for those and let's try to call them out

**Comment by t-vi** [comment]
I know I was the one to have everything called transform_trace, but it turns out that the scheme of transforms and subclasses creates a need to differentiate that would not be needed if we had just the Transform class with methods for the various stages, so: 
```
class Transform:
    def early_transform_traces(self, prologue_trace: Trace, computation_trace: Trace, epilogue_trace: Trace | None, **kwargs):
    def transform_module(self, model: thunder.ThunderModule):
    def transform_state_dict_for_submodule(...):
    def additional_transform_trace(self, computation_trace: Trace, **kwargs):  # but to be phased out
    def post_optimization_transform_trace(self, computation_trace: Trace, **kwargs):
```
The methods would default to returning unmodified args.

This allows users to pass in transforms regardless of their implementation (we currently have additional_transforms / early_transforms as separate arguments in places).
