### ISSUE TITLE
Indexing with slice and list

### ISSUE THREAD

**Issue by t-vi** [Lightning-AI/lightning-thunder#643]
Repro:

```
def fn(input_ids):
   return input_ids[:, [-1, 0]]

a = torch.randn(5, 5)
jfn = thunder.jit(fn)
jfn(a)
```

Needed for transformers BERT:

```
import thunder, torch, transformers

m = transformers.BertForSequenceClassification(transformers.BertConfig())
x = torch.randint(1, 10, (1, 32))
jm = thunder.jit(m)
jm(x)
```

Might ideally be fixed along with #460 and #187 

cc @apaz-cli @tfogal

**Comment by t-vi** [comment]
@k223kim wants to work on this. Thank you!

**Comment by k223kim** [comment]
Hey Team! I will be working on this issue. Thanks!

**Comment by tfogal** [comment]
triage review:
- can we modify the checker to test for this case and not send it to nvfuser until [the nvfuser bug](https://github.com/NVIDIA/Fuser/issues/2545) gets fixed?
- this is related to the NeVA model
- cc @kevinstephano

**Comment by jacobhinkle** [comment]
> until [the nvfuser bug](https://github.com/NVIDIA/Fuser/issues/2545) gets fixed?

FYI I'll merge https://github.com/NVIDIA/Fuser/pull/2547 soon which should address that bug.
