### ISSUE TITLE
Support the scatter operator

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#752]
## 🚀 Model / language coverage

Support for the [scatter](https://pytorch.org/docs/stable/generated/torch.scatter.html) operator.

### Pitch

This is [used in NeMo's NeVA model](https://github.com/NVIDIA/NeMo/blob/14d42dc599ff3d948f1e1271b1890d5b8c5fbd77/nemo/collections/multimodal/models/multimodal_llm/neva/neva_model.py#L259).

### Alternatives / Potential work-arounds

We can modify NeVA to not use the scatter op, if we could see some better way to implement the `replace_media_embeddings` method linked to above.

cc @apaz-cli @tfogal

**Comment by nikitaved** [comment]
Yeah, this one is long overdue. It is also very useful in some backward implementations where we could replace some occurrences of `scatter_add` with `scatter` potentially.
