### ISSUE TITLE
Apply `thunder.distributed.utils.sort_waits` appropriately when possible

### ISSUE THREAD

**Issue by crcrpar** [Lightning-AI/lightning-thunder#765]
https://github.com/Lightning-AI/lightning-thunder/pull/624 adds the support of `torch.distributed` ops notwithstanding the value of `async_op`. 
Even when `async_op=True`, thunder calls `wait` when the op is called, not when the `handle.wait` is called (Even, `handle.wait` is currently ignored).
So, it'd be better/required to apply `sort_waits` so that we have (at least) decent overlap of computation and communication.

Currently `sort_waits` and https://github.com/Lightning-AI/lightning-thunder/blob/f07027eb1f8ab97b39c5faa5a5b4a4beb1b1c91d/thunder/distributed/utils.py#L54 are only applied when `use_fsdp=True`.

cc @carmocca @crcrpar

**Comment by IvanYashchuk** [comment]
I agree, that the condition for the application of `sort_communication_ops` should be "Is `wait` present in the trace?".

@kiya00, since you're the person who contributed the most to this part of the project, could you please review the future pull request?
