### ISSUE TITLE
Error for falcon-40b from LitGPT

### ISSUE THREAD

**Issue by mpatel31415** [Lightning-AI/lightning-thunder#781]
## 🐛 Bug

When trying to check if [this issue](https://github.com/NVIDIA/Fuser/issues/2576) was fixed I've encountered another error: 

> An error occurred: BackendCompilerFailed – backend='inductor' raised:
SubprocException: An exception occurred in a subprocess:

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/compiler.py", line 292, in make_cubin
>     subprocess.run(cmd, shell=True, check=True)
>   File "/usr/lib/python3.10/subprocess.py", line 526, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '/usr/local/cuda/bin/ptxas -lineinfo -v --gpu-name=sm_90a /tmp/tmp3_7x2ycw.ptx -o /tmp/tmp3_7x2ycw.ptx.o 2> /tmp/tmpzru1tmde.log' returned non-zero exit status 255.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/compile_worker/subproc_pool.py", line 278, in do_job
>     result = job()
>   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/compile_tasks.py", line 68, in _worker_compile_triton
>     load_kernel().precompile(warm_cache_only=True)
>   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 234, in precompile
>     compiled_binary, launcher = self._precompile_config(
>   File "/usr/local/lib/python3.10/dist-packages/torch/_inductor/runtime/triton_heuristics.py", line 418, in _precompile_config
>     triton.compile(*compile_args, **compile_kwargs),
>   File "/usr/local/lib/python3.10/dist-packages/triton/compiler/compiler.py", line 282, in compile
>     next_module = compile_ir(module, metadata)
>   File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/compiler.py", line 320, in <lambda>
>     stages["cubin"] = lambda src, metadata: self.make_cubin(src, metadata, options, self.capability)
>   File "/usr/local/lib/python3.10/dist-packages/triton/backends/nvidia/compiler.py", line 297, in make_cubin
>     raise RuntimeError(f'Internal Triton PTX codegen error: \n{log}')
> RuntimeError: Internal Triton PTX codegen error: 
> ptxas /tmp/tmp3_7x2ycw.ptx, line 5; fatal   : Unsupported .version 8.6; current version is '8.5'
> ptxas fatal   : Ptx assembly aborted due to errors

### To Reproduce

Please use:

2 nodes, each with 8 GPUs.

Image "INTERNAL_IMAGE:pjnl-20240715"

Training script:

python /opt/pytorch/lightning-thunder/thunder/benchmarks/benchmark_litgpt.py
--model_name falcon-40b
--distributed_mode fsdp
--shard_mode zero3
--compile thunder_inductor_cat_cudnn
--checkpoint_activations False
--low_precision_mode none
--micro_batch_size 1

### Expected behavior

We get OOM error or the model runs. 

### Environment

As in the pjnl-20240715 image. 

### Additional context
Complete output from the cluster: 
[slurm-931326.txt](https://github.com/user-attachments/files/16249965/slurm-931326.txt)

**Comment by tfogal** [comment]
triage review:
@tfogal to connect with PyTorch team on this one; this has come up before

**Comment by xwang233** [comment]
This is an error related to internal tools. Please use the latest PJNL images. Thank you.
