### ISSUE TITLE
`index_copy_`: incorrect with CUDA inputs

### ISSUE THREAD

**Issue by nikitaved** [Lightning-AI/lightning-thunder#789]
Likely the cause of failures in https://github.com/Lightning-AI/lightning-thunder/pull/788
Take a look at the following repro:

```python
In [1]: import torch, thunder

In [2]: def f(x, idx, src):
   ...:     x.index_copy_(0, idx, src)
   ...:     return x
   ...: 

In [3]: jf = thunder.jit(f)

In [4]: x = torch.rand(3, 3)

In [5]: idx = torch.arange(3)

In [6]: src = torch.ones(3, 3)

In [7]: xx = x.clone()

In [8]: f(x, idx, src)
Out[8]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]: x
Out[9]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [10]: jf(xx, idx, src)
Out[10]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [11]: xx
Out[11]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]: x = torch.rand(3, 3).cuda()

In [13]: idx = idx.cuda()

In [14]: src = src.cuda()

In [15]: xx = x.clone()

In [16]: f(x, idx, src)
Out[16]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [17]: x
Out[17]: 
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [18]: jf(xx, idx, src)
Out[18]: 
tensor([[0.1944, 0.2947, 0.2669],
        [0.3471, 0.5339, 0.4950],
        [0.9053, 0.2321, 0.0383]], device='cuda:0')

In [19]: xx
Out[19]: 
tensor([[0.1944, 0.2947, 0.2669],
        [0.3471, 0.5339, 0.4950],
        [0.9053, 0.2321, 0.0383]], device='cuda:0')
```

This is the trace:
```python
# Constructed by Delete Last Used (took 0 milliseconds)
import torch
from thunder.executors.torchex import no_autocast

@torch.no_grad()
@no_autocast
def computation(x, idx, src):
  # x: "cuda:0 f32[3, 3]"
  # idx: "cuda:0 i64[3]"
  # src: "cuda:0 f32[3, 3]"
  t0 = torch.index_copy(x, 0, idx, src)  # t0: "cuda:0 f32[3, 3]"
    # t0 = ltorch.index_copy(x, 0, idx, src)  # t0: "cuda:0 f32[3, 3]"
      # t0 = prims.index_copy(x, idx, src, 0)  # t0: "cuda:0 f32[3, 3]"
  del idx, src
  nvFusion0(t0, x)
    # prims.copy_(t0, x)
  del t0
  return x
```

**Comment by nikitaved** [comment]
I suspect there is something going on on the boundary between the op and the fusion region. A quick look at `torch/__init__.py` shows that all in-place ops that are present there have their representative in the nvfuserex, and so they are being put inside a fusion region along with the copy. Copy alone works, but a non-nvfuser prim + copy does not. cc @crcrpar

**Comment by nikitaved** [comment]
We should probably also have a look at how `copy_` behaves when it is the only op in the fusion. Looks like no kernels are being launched, judging from https://github.com/Lightning-AI/lightning-thunder/blob/29379ec825c6101888c4c3d5af4e4a7cbf475b24/thunder/executors/nvfuserex_impl.py#L2036-L2046

**Comment by jjsjann123** [comment]
> We should probably also have a look at how `copy_` behaves when it is the only op in the fusion. Looks like no kernels are being launched, judging from
> 
> https://github.com/Lightning-AI/lightning-thunder/blob/29379ec825c6101888c4c3d5af4e4a7cbf475b24/thunder/executors/nvfuserex_impl.py#L2036-L2046
> 
> 
> Is my assessment correct? (No CUDA env available to test it at the moment...)

sorry for the late response.

You were right about that. But that's not the right behavior. codegen should be smart enough to figure out when to launch a kernel to realize the inplace update.
I'm [patching it](https://github.com/NVIDIA/Fuser/pull/2638) and we should be able to [revert the WAR in thunder](https://github.com/Lightning-AI/lightning-thunder/pull/806) afterwards.
