### ISSUE TITLE
`prims.copy_` with NVFuser: sometimes it has to be a kernel.

### ISSUE THREAD

**Issue by nikitaved** [Lightning-AI/lightning-thunder#791]
Have a look at the impl of `copy_` in the nvfuserex:
https://github.com/Lightning-AI/lightning-thunder/blob/29379ec825c6101888c4c3d5af4e4a7cbf475b24/thunder/executors/nvfuserex_impl.py#L2036-L2046

So, we can see that, apparently, no kernels are being actually launched, unless an op and a copy op are fused together. In the context of in-place ops, take a look at our `torch/__init__.py` in-place ops and note that they are represented in the nvfuserex.

Sometimes we might need an in-place op which does not have an equivalent in NVFuser.
This might lead to silent no-op issues like https://github.com/Lightning-AI/lightning-thunder/issues/789, where `copy_` ends up being the only op in the fusion and, as a result, does nothing.

cc @tfogal

**Comment by tfogal** [comment]
cc @crcrpar @jjsjann123

**Comment by nikitaved** [comment]
Potential fix in https://github.com/Lightning-AI/lightning-thunder/pull/788

**Comment by jjsjann123** [comment]
sorry for jumping in late.... But this looks like an nvfuser issue. i.e. if we are copying from a fusion input, we should have called a set on the copy_from.

Actually, we could have always called a set on copy_from. But looks like even with that, nvfuser isn't running a kernel on that and that's wrong we need to patch that.

**Comment by jjsjann123** [comment]
Thanks a lot for the repro and quick patch @nikitaved . :bow: 

I'll follow up and fix nvfuser side properly.

**Comment by jjsjann123** [comment]
A toy repro for myself
```
import thunder
import torch

def foo(x, y, idx, src):
    x.index_copy_(0, idx, src)
    z = x + 1
    y.index_copy_(0, idx, src)
    return x, y, z
    #return x, y
 
jfoo = thunder.jit(foo)
 
x = torch.randn(5, 5, device="cuda")
y = torch.randn(5, 5, device="cuda")
idx = torch.arange(5).cuda()
src = torch.ones(5, 5, device="cuda")
 
xx = x.clone()
yy = y.clone()
foo(x, y, idx, src)
jfoo(xx, yy, idx, src)
 
print(thunder.last_traces(jfoo)[-1])
assert(x.allclose(xx))
assert(y.allclose(yy))
```

**Comment by jjsjann123** [comment]
nvfuser behavior is being patched in https://github.com/NVIDIA/Fuser/pull/2638

Meanwhile, I'm reverting the thunder logic in: #806
