### ISSUE TITLE
Support for torch autocasting

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#796]
## 🚀 Model / language coverage

Having an issue with a customer model because we do not emulate or respect autocast. This in turn means the model does not fit.

### Pitch

This is an NVIDIA customer model.

### Alternatives / Potential work-arounds

I tried just casting the model to fp16 explicitly via `to()`, but there are type issues with this approach (probably another bug, still simplifying it for a second issue).

### Minimal Repro

```python
import torch
import torch.nn as nn
import thunder

class ProxyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()

        self.mp2d = nn.MaxPool2d(kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), dilation=1, ceil_mode=False)
        self.c0 = nn.Conv2d(96, 96, kernel_size=(1, 1), stride=(1, 1))
    
    def forward(self):
        with torch.amp.autocast('cuda', enabled=True):
            i0 = torch.randn((22, 96, 120, 160), device="cuda")
            t0 = self.mp2d(i0)
            t1 = self.c0(t0)
            print(f"t1 shape:dtype={t1.shape}:{t1.dtype}")
            return t1

m = ProxyModel().cuda()
print("eager:")
with torch.amp.autocast('cuda', enabled=True):
  eager = m()
  mdl = thunder.jit(m)
  print("thunder:")
  thund = mdl()
  print(f"eager shape:dtype={eager.shape}:{eager.dtype}")
  print(f"thunder shape:dtype={thund.shape}:{thund.dtype}")
```

Note that `autocast`ing twice is irrelevant; torch will make `t1` be `torch.float16` with either of the two. I only put them in twice to make it clear that thunder is ignoring the `with` context both when it's part of the `jit`ted function and when it's coming from the outer context.

**Comment by t-vi** [comment]
As far as I can tell, we need autocast for conv layers in thunder.core.transforms. I'll try.
