### ISSUE TITLE
Matmul lowering expands tensor input leading to 100x+ slowdown

### ISSUE THREAD

**Issue by parthmannan** [Lightning-AI/lightning-thunder#872]
## 🐛 Bug

This was discovered while trying to debug why NeMo NeVA using Dynamo+Thunder was orders of magnitude slower than Eager mode.
The issue is that the Matmul lowering/decomposition broadcasts the weight tensor to match the batch size of the input, i.e., if the input tensor is `[b, s, h]` and weight tensor is `[h, h2]`, the weight tensor is expanded to `[b, h, h2]` leading to a much slower BMM. The issue exists outside of Dynamo integration as well.

### To Reproduce

This is a mini-repro script for one of the GEMMs inside NeVA model.
```
import torch
import torch.nn as nn
import thunder

class mm_Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(5120, 15360), requires_grad=True)

    def forward(self, x):
        return torch.matmul(x, self.weight)

mm_net = mm_Model().to(torch.bfloat16).cuda()
mm_net = thunder.jit(mm_net)

for x in range(10):
    input_tensor = torch.randn([384, 2, 5120], dtype=torch.bfloat16, device='cuda', requires_grad=True)
    target_tensor = torch.randn([384, 2, 15360], dtype=torch.bfloat16, device='cuda')

    if x == 5:
        torch.cuda.cudart().cudaProfilerStart()

    output = mm_net(input_tensor)
    output.backward(target_tensor)

    # print(thunder.last_traces(mm_net)[-1])

    if x == 5:
        torch.cuda.cudart().cudaProfilerStop()
```

Running the script directly with Thunder will lead to (which might be a separate issue on its own)
```
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 56.25 GiB. GPU 0 has a total capacity of 79.11 GiB of which 21.79 GiB is free. Including non-PyTorch memory, this process has 57.31 GiB memory in use. Of the allocated memory 439.00 MiB is allocated by PyTorch, and 56.24 GiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

Use `PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True python thunder_expand_mm_bmm.py`

Generated trace
 ```
 # Constructed by Delete Last Used (took 0 milliseconds)
import torch
from torch import Tensor
from thunder.executors.torchex import no_autocast

@torch.no_grad()
@no_autocast
def augmented_forward_fn(x, t_weight):
  # x: "cuda:0 bf16[384, 2, 5120]"
  # t_weight: "cuda:0 bf16[5120, 15360]"
  t3 = torch.unsqueeze(t_weight, 0)  # t3: "cuda:0 bf16[1, 5120, 15360]"
    # t3 = ltorch.unsqueeze(t_weight, 0)  # t3: "cuda:0 bf16[1, 5120, 15360]"
      # t3 = prims.broadcast_in_dim(t_weight, [1, 5120, 15360], [1, 2])  # t3: "cuda:0 bf16[1, 5120, 15360]"
  t0 = Tensor.expand(t3, (384, 5120, 15360))  # t0: "cuda:0 bf16[384, 5120, 15360]"
    # t0 = ltorch.expand(t3, (384, 5120, 15360))  # t0: "cuda:0 bf16[384, 5120, 15360]"
      # t0 = prims.broadcast_in_dim(t3, (384, 5120, 15360), (0, 1, 2))  # t0: "cuda:0 bf16[384, 5120, 15360]"
  del t3
  t1 = torch.matmul(x, t0)  # t1: "cuda:0 bf16[384, 2, 15360]"
    # t1 = ltorch.matmul(x, t0)  # t1: "cuda:0 bf16[384, 2, 15360]"
      # t1 = prims.matmul(x, t0)  # t1: "cuda:0 bf16[384, 2, 15360]"
  return {'output': t1, 'flat_args': [x, t_weight], 'flat_output': (t1,)}, ((t0, x), ()
```

We can see that t_weight is expanded from `[5120, 15360]` into `[384, 5120, 15360]`

Matmul without Thunder.jit creates a MM kernel which takes **0.169ms** to execute.
Matmul with this expanded tensor creates a Batched MM (BMM) kernel which takes **18.36ms** to execute which is a 108x slowdown.

cc - @tfogal 

cc @apaz-cli @tfogal

**Comment by mruberry** [comment]
> It's a PyTorch bug that it materializes the batch dimensions instead of using the 0 stride for the batch dimension. It's a rather old problem ([discuss.pytorch.org/t/matmul-broadcasting-makes-copies/19494](https://discuss.pytorch.org/t/matmul-broadcasting-makes-copies/19494)). Thunder's explicit broadcasting is a good thing and maybe we shouldn't introduce special cases for matmul. It's the executor's job to recognize the broadcast inputs and make use of the strides. Instead of using `torch.matmul` directly here [`d202ba3`/thunder/executors/torchex.py#L1332C10-L1332C35](https://github.com/Lightning-AI/lightning-thunder/blob/d202ba3d868642e0b4d61cd1bf93794350d5a663/thunder/executors/torchex.py#L1332C10-L1332C35) there could be a wrapper that checks whether one of the inputs is broadcast in the batch dimensions and call `torch.matmul(a, b[0])` instead of `torch.matmul(a, b)`.

Fixing this in the PyTorch executor would be great. 

> Another possible general solution is to reconsider doing the explicit broadcasting as "unsqueeze + expand" to do only the "unsqueeze" and leave the broadcast dimensions as `1`. This would resolve this performance bug and I think we discussed in the past that it would be more compatible with nvFuser's way of defining fusions with dynamic shapes.

We can do this, but we should file a separate issue for it. We'd have to change the primitive's semantics to allow for broadcasting dimensions of length 1. This would be more consistent with JAX's lax operations, which support broadcasting but not type promotion.

> If the original code used the equivalent `torch.nn.functional.linear(x, self.weight.T)` then there wouldn't be performance regression with Thunder.

@parthmannan What do you think of making this change as a workaround?

**Comment by parthmannan** [comment]
>Thunder's explicit broadcasting is a good thing and maybe we shouldn't introduce special cases for matmul.
I am not familiar with the underlying reason so curious to understand why the explicit broadcasting is needed here (or generally in Thunder)? I don't see any perf regression with Eager/TorchInductor despite the old PyTorch executor bug. Is this because Eager/Inductor don't need to broadcast?

>@parthmannan What do you think of making this change as a workaround?
We can check with folks from NeMo but NeMo and Megatron-LM codebases are huge and needs very broad performance testing and time before such a change is accepted (even though it should be equivalent) so this would require quite a bit of justification to make such a change.
In general, Matmul having this performance regression only in Thunder is something I feel we'll run into often as we support more models so a native solution would be much better.

**Comment by tfogal** [comment]
@nikitaved has graciously agreed to take this on. Thanks Nik!

**Comment by nikitaved** [comment]
With the patch the trace looks like this now:
```python
import torch
from thunder.executors.torchex import no_autocast

@torch.no_grad()
@no_autocast
def augmented_forward_fn(x, t_weight):
  # x: "cuda:0 bf16[384, 2, 5120]"
  # t_weight: "cuda:0 bf16[5120, 15360]"
  t0 = torch_prims_reshape_impl(x, (768, 5120))  # t0: "cuda:0 bf16[768, 5120]"
  t1 = torch.matmul(t0, t_weight)  # t1: "cuda:0 bf16[768, 15360]"
    # t1 = ltorch.matmul(t0, t_weight)  # t1: "cuda:0 bf16[768, 15360]"
      # t1 = prims.matmul(t0, t_weight)  # t1: "cuda:0 bf16[768, 15360]"
  t3 = torch_prims_reshape_impl(t1, (384, 2, 15360))  # t3: "cuda:0 bf16[384, 2, 15360]"
  del t1
  return {'output': t3, 'flat_args': [x, t_weight], 'flat_output': (t3,)}, ((t0, t_weight), ())

```

**Comment by csarofeen** [comment]
Awesome approach. Thanks Nik!

**Comment by csarofeen** [comment]
@jjsjann123 I wonder how this would interact with dynamic shapes, would we want reshapes to potentially be symbolic. i.e. the reshape in Nik's approach being something like `reshape(x, (-1, x.size(2)))`?

**Comment by jjsjann123** [comment]
> @jjsjann123 I wonder how this would interact with dynamic shapes, would we want reshapes to potentially be symbolic. i.e. the reshape in Nik's approach being something like `reshape(x, (-1, x.size(2)))`?

Is the question asking about the API, i.e. if we plan to distinguish `size` vs `shape` and make one accessing `static` shape while the other the `symbolic` shape.

If we follow the plan where we allow TensorProxy.shape contain NumberProxy, then @nikitaved ' fixes are already **trying** to use the proper tensor shape symbols https://github.com/Lightning-AI/lightning-thunder/blob/006ba4e3e5a1dc167cd0b634bcedc7419136f054/thunder/torch/__init__.py#L3369-L3378
