### ISSUE TITLE
TypeError: rms_forward_affine_mixed_dtypes(): incompatible function arguments

### ISSUE THREAD

**Issue by tfogal** [Lightning-AI/lightning-thunder#896]
## 🚀 Model / language coverage

```
[rank0]:   File "/home/tfogal/dev/nemo/nemo/collections/nlp/modules/common/megatron/language_model.py", line 824, in forward
[rank0]:     encoder_output = self.encoder(
[rank0]:   File "/home/tfogal/dev/thunder/thunder/core/interpreter.py", line 6372, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1716, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/home/tfogal/dev/thunder/thunder/core/interpreter.py", line 6372, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1727, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/home/tfogal/dev/thunder/thunder/core/interpreter.py", line 6372, in _impl
[rank0]:     return fn.__func__(fn.__self__, *args, **kwargs)
[rank0]:   File "/home/tfogal/dev/nemo/nemo/collections/nlp/modules/common/megatron/transformer.py", line 1632, in forward
[rank0]:     hidden_states = layer(
[rank0]: TypeError: rms_forward_affine_mixed_dtypes(): incompatible function arguments. The following argument types are supported:
[rank0]:     1. (arg0: torch.Tensor, arg1: Tuple[int, ...], arg2: torch.Tensor, arg3: float) -> list[torch.Tensor]

[rank0]: Invoked with: <TensorProxy(name="t4161", dtype=thunder.dtypes.float16, shape=(384, 2, 5120))>, torch.Size([5120]), <TensorProxy(name="t4162", dtype=thunder.dtypes.float16, shape=(5120,))>, 1e-05
```

[full log of the run](https://github.com/user-attachments/files/16444645/neva.txt)

### Pitch

This comes up in the pure-thunder path to supporting NeVA

### Alternatives / Potential work-arounds

We could just use the dynamo frontend, for now.

### Minimal Repro

Still working on this ...

cc @apaz-cli @tfogal

**Comment by tfogal** [comment]
triage review:
* this is a C-defined function that does not have a lookaside
* not a great error message for this :-(. would be great to see a clearer error message
* need to add this op as a thunder op

**Comment by kshitij12345** [comment]
need to add this op as a thunder op : I think we can do this for this particular case, but in future we might stumble upon other such cases. Wouldn't it be easier to have a mechanism like discussed in https://github.com/Lightning-AI/lightning-thunder/issues/816 and let the user deal with this?

**Comment by kshitij12345** [comment]
Another option is a utility function in thunder to mark users functions such that they will show up in trace as symbols and the implementation will be calling operation with unwrapped values (and it also needs to provide ability to register grad rule). Though, we will need to figure out a way to create a meta function (can FakeTensors be used here?)

Example
```python
thunder.wrap_as_opaque_symbol(fn=my_opaque_fn, grad_rule=my_opaque_fn_grad_rule)
```

Computation Trace
```python
t1 = my_opaque_fn(x, y)
```

**Comment by tfogal** [comment]
Thanks for your comments and for owning this, Kshiteej!

Yes, this sounds a lot like the [torch.compiler.allow_in_graph](https://pytorch.org/docs/stable/generated/torch.compiler.allow_in_graph.html) concept. I agree that we shouldn't be satisfied with a one-off solution here, although I'd be supportive of committing a temporary one-off solution while we worked on something like #816.
